/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-07-03 11:24:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.logonPage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class entryPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html class=\"full\" lang=\"ko\">\n");
      out.write("\n");
      out.write("<!-- Make sure the <html> tag is set to the .full CSS class. Change the background image in the full.css file. -->\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("\t\t\t<meta http-equiv = \"Content-Type\" content=\"text/html; charset=utf-8\">\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta name=\"author\" content=\"\">\n");
      out.write("\n");
      out.write("    <title>Start BuzzCloud</title>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap Core CSS -->\n");
      out.write("    <link href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7\" crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("    <!-- Custom CSS -->\n");
      out.write("    <link href=\"/css/logonPage/mainpage.css?<?=filemtime(\\'./css/readizgen.css\\')?\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("\t\t\t<link href=\"/css/logonPage/form.css?<?=filemtime(\\'./css/readizgen.css\\')?\" rel=\"stylesheet\" type=\"text/css\"><!--  -->\n");
      out.write("\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n");
      out.write("    <!--[if lt IE 9]>\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\n");
      out.write("    <![endif]-->\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t\t\t<div id=\"mask\">\n");
      out.write("\t\t\t</div> \n");
      out.write("\n");
      out.write("\t\t\t<div class=\"joinModal\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t<div class=\"text-vertical-center\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\n");
      out.write("\t\t\t\t  <div class=\"modal-dialog\">\n");
      out.write("\t\t\t\t  <div class=\"modal-content\">\n");
      out.write("\t\t\t\t      <div class=\"modal-header\">\n");
      out.write("\t\t\t\t          <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">×</button>\n");
      out.write("\t\t\t\t          <h1 class=\"text-center\">버즈클라우드에 가입하기 </h1>\n");
      out.write("\t\t\t\t      </div>\n");
      out.write("\t\t\t\t      <div class=\"modal-body\">\n");
      out.write("\t\t\t\t      \n");
      out.write("\t\t\t\t          <form class=\"form col-md-12 center-block\" id=\"innerJoinForm\" method=\"GET\" ACTION=\"join.do\">\n");
      out.write("\t\t\t\t            <div class=\"form-group\">\n");
      out.write("         \t\t\t\t\t\t\t <input type=\"text\" name=\"email\" class=\"form-control input-lg\" placeholder=\"Email\">\n");
      out.write("\t\t\t\t            </div>\n");
      out.write("\t\t\t\t            <div class=\"form-group\">\n");
      out.write("         \t\t\t\t\t\t\t <input type=\"text\" name=\"nickname\" class=\"form-control input-lg\" placeholder=\"Nickname\">\n");
      out.write("\t\t\t\t            </div>\n");
      out.write("\t\t\t\t            <div class=\"form-group\"> \n");
      out.write("\t\t\t\t             <input type=\"password\" name=\"password\" class=\"form-control input-lg\" placeholder=\"Password\">\n");
      out.write("\t\t\t\t            </div>\n");
      out.write("\t\t\t\t             <div class=\"form-group\"> \n");
      out.write("\t\t\t\t              <input type=\"password\" name=\"inner_password2\" class=\"form-control input-lg\" placeholder=\"Rewrite Password\">\n");
      out.write("\t\t\t\t            </div>\n");
      out.write("\t\t\t\t            <div class=\"form-group\">\n");
      out.write("\t\t\t\t              <button class=\"btn btn-primary btn-lg btn-block\" onClick=\"innerJoin()\" >가입하기</button>\n");
      out.write("\t\t\t\t              <span class=\"pull-right\"><a href=\"#\">로그인하기</a></span><span><a href=\"#\">가입하면 무엇이 좋나요?</a></span>\n");
      out.write("\t\t\t\t            </div>\n");
      out.write("\t\t\t\t            \t\t\t\n");
      out.write("\t\t\t\t            \t<input type=\"hidden\" name=\"idType\" value=\"inner\">\n");
      out.write("\t\t\t\t          </form>\n");
      out.write("\t\t\t\t         \t\t\n");
      out.write("\t\t\t\t      </div>\n");
      out.write("\t\t\t\t      <div class=\"modal-footer\">\n");
      out.write("\t\t\t\t          <div class=\"col-md-12\">\n");
      out.write("\t\t\t\t          <button class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">Cancel</button>\n");
      out.write("\t\t\t\t\t\t  </div>\t\n");
      out.write("\t\t\t\t      </div>\n");
      out.write("\t\t\t\t  </div>\n");
      out.write("\t\t\t\t  </div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"logonModal\"> \n");
      out.write("\t\t\t\t<div class=\"text-vertical-center\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\n");
      out.write("\t\t\t\t  <div class=\"modal-dialog\">\n");
      out.write("\t\t\t\t  <div class=\"modal-content\">\n");
      out.write("\t\t\t\t      <div class=\"modal-header\">\n");
      out.write("\t\t\t\t          <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">×</button>\n");
      out.write("\t\t\t\t          <h1 class=\"text-center\">버즈클라우드에 로그인</h1>\n");
      out.write("\t\t\t\t      </div>\n");
      out.write("\t\t\t\t      <div class=\"modal-body\">\n");
      out.write("\t\t\t\t      \n");
      out.write("\t\t\t\t          <form class=\"form col-md-12 center-block\"  id=\"innerLogonForm\" method=\"GET\" ACTION=\"innerLogon.do\" >\n");
      out.write("\t\t\t\t            <div class=\"form-group\">\n");
      out.write("\t\t\t\t              <input type=\"text\" name=\"inner_email\" class=\"form-control input-lg\" placeholder=\"Email\">\n");
      out.write("\t\t\t\t            </div>\n");
      out.write("\t\t\t\t            <div class=\"form-group\"> \n");
      out.write("\t\t\t\t              <input type=\"password\" name=\"inner_password\" class=\"form-control input-lg\" placeholder=\"Password\">\n");
      out.write("\t\t\t\t            </div>\n");
      out.write("\t\t\t\t            <div class=\"form-group\">\n");
      out.write("\t\t\t\t              <button class=\"btn btn-primary btn-lg btn-block\" onClick=\"innerLogon()\" >로그인하기</button>\n");
      out.write("\t\t\t\t              <span class=\"pull-right\"><a href=\"#\">가입하기</a></span><span><a href=\"#\">가입하면 무엇이 좋나요?</a></span>\n");
      out.write("\t\t\t\t            </div>\n");
      out.write("\t\t\t\t            \n");
      out.write("\t\t\t\t            \t<input type=\"hidden\" name=\"kind\" value=\"inner\">\n");
      out.write("\t\t\t\t          </form>\n");
      out.write("\t\t\t\t         \t\t\n");
      out.write("\t\t\t\t      </div>\n");
      out.write("\t\t\t\t      <div class=\"modal-footer\">\n");
      out.write("\t\t\t\t          <div class=\"col-md-12\">\n");
      out.write("\t\t\t\t          <button class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">Cancel</button>\n");
      out.write("\t\t\t\t\t\t  </div>\t\n");
      out.write("\t\t\t\t      </div>\n");
      out.write("\t\t\t\t  </div>\n");
      out.write("\t\t\t\t  </div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("   <!-- Navigation -->\n");
      out.write("\n");
      out.write("    <nav class=\"navbar navbar-inverse navbar-fixed-bottom\" role=\"navigation\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <!-- Brand and toggle get grouped for better mobile display -->\n");
      out.write("            <div class=\"navbar-header\">\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                </button>\n");
      out.write("                <a class=\"navbar-brand\" href=\"#\">BuzzCloud</a>\n");
      out.write("            </div>\n");
      out.write("            <!-- Collect the nav links, forms, and other content for toggling -->\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\n");
      out.write("                <ul class=\"nav navbar-nav\">\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\">버즈클라우드?</a>\n");
      out.write("                    </li>                 \n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\">어떻게 사용하죠?</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\">문제점보고와 건의사항</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\">개발자와 연락하기</a>\n");
      out.write("                    </li>\t\t\n");
      out.write("                     <li>\n");
      out.write("                        <a href=\"#\" id=\"toJoin\" >버즈클라우드에 가입하기 </a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <!-- /.navbar-collapse -->\n");
      out.write("        </div>\n");
      out.write("        <!-- /.container -->\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <!-- Page Content -->\n");
      out.write("\t\t\t\t\t    \n");
      out.write("\t\t\t\t\t<header id=\"top\" class=\"header\">\n");
      out.write("\t\t\t\t    <div class=\"text-vertical-center\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<h1>버즈클라우드</h1>\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t        \t\t<h3>생산적인 팀 프로젝트를 위해<br> \n");
      out.write("\t\t        \t\t\t\t\t사용해보세요</h3>\n");
      out.write("    \t\t\t\t\t\t\t<br><br>\n");
      out.write("    \t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"BUTTON\" id=\"toLogon\" class=\"btn btn-dark btn-lg\"  value=\"사이트 로그인하기 \"  >  <br><br>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"naver_id_login\"></div>\n");
      out.write("\t\t\t    </div> \n");
      out.write("\t    </header>\n");
      out.write("    <!-- /.container -->\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" charset=\"utf-8\" src=\"http://code.jquery.com/jquery-latest.js\"></script>\n");
      out.write("<script type=\"text/javascript\" charset=\"utf-8\" src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.0/jquery.cookie.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" charset=\"utf-8\" src=\"https://static.nid.naver.com/js/naverLogin_implicit-1.0.2.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Bootstrap Core JavaScript -->\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("\t\n");
      out.write("\t\tvar mail;\n");
      out.write("\t\tvar nick;\n");
      out.write("\t\t\n");
      out.write("\t\tvar naver = new naver_id_login(\"Vf8cYbYQv2N0c_cSv_XA\", \"http://114.129.211.33:8181/\");\n");
      out.write("\t\tvar state = naver.getUniqState();\n");
      out.write("\t\tnaver.setState(state);\n");
      out.write("\t\tnaver.setButton(BUTTON_COLOR_GREEN, BANNER_BIG_TYPE, 40);\n");
      out.write("\t\tnaver.setStateStore();\n");
      out.write("\t\tnaver.init_naver_id_login();\t \n");
      out.write(" \n");
      out.write("\t\tgetParameter = function(param){\n");
      out.write("\t\t    full_url=location.href;\n");
      out.write("\t\t    \n");
      out.write("\t\t  \t\t\t//파라미터가 하나도 없을때\n");
      out.write("\t\t    if(full_url.search(\"&\") == -1)\n");
      out.write("\t\t        return false;\n");
      out.write("\n");
      out.write("\t\t  \t\t\tif(full_url.indexOf(\"#\") != -1)\n");
      out.write("\t\t    \t\t\t\tsearch=full_url.split(\"#\");\n");
      out.write("\t\t  \t\t\telse if(full_url.indexOf(\"?\") != -1)\n");
      out.write("\t\t  \t\t\t\t\tsearch=full_url.split(\"?\");\n");
      out.write("\t\t  \t\t\telse\n");
      out.write("\t\t  \t\t\t\t\treturn null;\n");
      out.write("\t\t  \t\t\t\n");
      out.write("\t\t\t\t    //해당하는 파라미터가 없을때.\n");
      out.write("\t\t    if(search[1].indexOf(param)==(-1)){\n");
      out.write("\t\t        \n");
      out.write("\t\t        return \"\";\n");
      out.write("\t\t        return;\n");
      out.write("\t\t\t\t    }\n");
      out.write("\t\t    \n");
      out.write("\t\t    search=search[1].split(\"&\");\n");
      out.write("\n");
      out.write("\t\t   \t\t //한개의 파라미터일때.\n");
      out.write("\t\t    if(search.length<3){\n");
      out.write("\t\t       \n");
      out.write("\t\t        data=search[1].split(\"=\");\n");
      out.write("\t\t        return data[1];\n");
      out.write("\t\t\t\t    }\n");
      out.write("\t\t    else{\n");
      out.write("\t\t\t\t    //여러개의 파라미터 일때.\n");
      out.write("\t\t\t    var i=0;\n");
      out.write("\t\t    \t\tfor(i=0 ; i < search.length ; i++){\n");
      out.write("\t\t    \t\t\t\tdata = search[i].split(\"=\");\n");
      out.write("\t\t\t    \t\t\tif(data[0].match(param))\n");
      out.write("\t\t\t    \t\t\t\treturn data[1];\n");
      out.write("\t\t    \t\t\t}\n");
      out.write("\t\t\t    \tif(i==search.length)\n");
      out.write("\t\t    \t\t\t\treturn NULL;\n");
      out.write("\t\t    \t\t}\n");
      out.write("\t\t    \n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\twindow.onload=function(){\n");
      out.write("\t\t\t");

	
			/*  logonBean으로 부터 넘어온 값을 읽어 로그인 성공이 된 경우 로그인유지를 위해 세션에 별도의 값을 저장한다. */

				try{ 
					//이미 로그인 했던 기록이 있다면 자동로그인 한다.   
					if( session.getAttribute("alreadyLogon") != null &&
							((String) session.getAttribute("alreadyLogon")).equals("true")){
									response.sendRedirect("/main.do");
					}
					//Oauth 콜백을 처리 후 가입결과를 반환받아 성공하였다면 로그인처리한다.
					else if( request.getAttribute("oauthJoin")!= null ||	request.getAttribute("innerJoin") != null) 	{
						
      out.write("\n");
      out.write("\t\t\t\t\t\t\talert( ");
      out.print( (String)request.getAttribute("message") );
      out.write(" );\n");
      out.write("\t\t\t\t\t\t");
			
						session.setAttribute("alreadyLogon", "true");
						response.sendRedirect("/main.do");

					}
					else if( request.getAttribute("innerLogon")!= null){
						if( 	((String)request.getAttribute("innerLogon")).equals("true") == true){

							session.setAttribute("alreadyLogon", "true");
							response.sendRedirect("/main.do");
						}
						else if(	((String)request.getAttribute("innerLogon")).equals("false") == true){
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\talert( ");
      out.print( (String)request.getAttribute("message") );
      out.write(" );\n");
      out.write("\t\t\t\t\t\t\t");

														
						}
					}
					
					else{
					
      out.write("\n");
      out.write("\t\t\t//네이버로그인 콜백인지 확인 \n");
      out.write("\t\t\t\t\t\tvar state = getParameter(\"state\");\n");
      out.write("\t\t\t\t\t\tif(state == null)\n");
      out.write("\t\t\t\t\t\t\tconsole.log(\"error of urlpaser\");\n");
      out.write("\t\t\t\t\t\tvar savedNaverState = naver.state;\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\tif( state.match(savedNaverState) ){\n");
      out.write("\t\t\t\t\t\t\t\tnaver.get_naver_userprofile(\"setHiddenForm()\");\t\t\t\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t");

				}//else
			}//try
			catch(Exception e){
				e.printStackTrace();}
					
			
      out.write("\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t function wrapLogonModal(){\n");
      out.write("\t\t\t        //화면의 높이와 너비를 구한다.\n");
      out.write("        var maskHeight = $(document).height();  \n");
      out.write("        var maskWidth = $(window).width();  \n");
      out.write("\n");
      out.write("        //마스크의 높이와 너비를 화면 것으로 만들어 전체 화면을 채운다.\n");
      out.write("        $('#mask').css({'width':maskWidth,'height':maskHeight});  \n");
      out.write("\t\t\t\t\t$('#mask').fadeTo(\"slow\",0.8);      \n");
      out.write("\t\t\t\t\t\t$('.logonModal').show();\n");
      out.write("\t\t\t}\n");
      out.write("\t\t \n");
      out.write("\t\t function wrapJoinModal(){\n");
      out.write("\t\t\t        //화면의 높이와 너비를 구한다.\n");
      out.write("\t\t\t\t var maskHeight = $(document).height();  \n");
      out.write("\t\t\t\t var maskWidth = $(window).width();  \n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t //마스크의 높이와 너비를 화면 것으로 만들어 전체 화면을 채운다.\n");
      out.write("\t\t\t\t $('#mask').css({'width':maskWidth,'height':maskHeight});  \n");
      out.write("\t\t\t\t\t$('#mask').fadeTo(\"slow\",0.8);      \n");
      out.write("\t\t\t\t\t$('.joinModal').show();\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t \n");
      out.write("\t\t $(document).ready(function(){ \n");
      out.write("\t\t\t\t\t\t\t$(\t'#toLogon').click(function(e){\n");
      out.write("\t\t\t\t\t\t\t\te.preventDefault();\n");
      out.write("\t\t\t\t\t\t\t\twrapLogonModal();\n");
      out.write("\t\t\t\t\t\t\t});\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t$(\t'#toJoin').click(function(e){\n");
      out.write("\t\t\t\t\t\t\t\te.preventDefault();\n");
      out.write("\t\t\t\t\t\t\t\twrapJoinModal();\n");
      out.write("\t\t\t\t\t\t\t});\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t//닫기 버튼을 눌렀을 때\n");
      out.write("\t\t\t\t\t\t\t$('.logonModal .close').click(function (e) {  \n");
      out.write("\t\t\t\t\t\t\t    //링크 기본동작은 작동하지 않도록 한다.\n");
      out.write("\t\t\t\t\t\t\t    e.preventDefault();  \n");
      out.write("\t\t\t\t\t\t\t    $('#mask, .logonModal').hide();  \n");
      out.write("\t\t\t\t\t\t\t});   \n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t$('.joinModal .close').click(function (e) {  \n");
      out.write("\t\t\t\t\t\t\t\t    //링크 기본동작은 작동하지 않도록 한다.\n");
      out.write("\t\t\t\t\t\t\t\t    e.preventDefault();  \n");
      out.write("\t\t\t\t\t\t\t\t    $('#mask, .joinModal').hide();  \n");
      out.write("\t\t\t\t\t\t\t\t});   \n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t//검은 wrapLogonModal 눌렀을 때\n");
      out.write("\t\t\t\t\t\t\t$('#mask').click(function () {  \n");
      out.write("\t\t\t\t\t\t\t\t    $(this).hide();  \n");
      out.write("\t\t\t\t\t\t\t\t    $('.logonModal').hide();  \n");
      out.write("\t\t\t\t\t\t\t\t    $('.joinModal').hide();\n");
      out.write("\t\t\t\t\t\t\t\t});\n");
      out.write("\t\t })\n");
      out.write("\t\t\t\n");
      out.write("\t\tfunction setHiddenForm(){\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tmail = naver.getProfileData('email');\n");
      out.write("\t\t\tnick = naver.getProfileData('nickname');\n");
      out.write("\t\t\tdocument.getElementsByName(\"email\")[1].value = mail;\n");
      out.write("\t\t\tdocument.getElementsByName(\"nickname\")[1].value = nick;\n");
      out.write("\t\t\tdocument.getElementsByName(\"password\")[1].value = \"\";\n");
      out.write("\t\t\tdocument.getElementsByName(\"idType\")[1].value = \"naver\";\n");
      out.write("\t\t\tdocument.forms[\"joinForm\"].submit();\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t \n");
      out.write("\tfunction innerJoin(){\n");
      out.write("\t\t\t \n");
      out.write("\t\t\t\tdocument.getElementsByName(\"email\")[1].value = document.getElementById(\"inner_email\").value;\n");
      out.write("\t\t\t\tdocument.getElementsByName(\"nickname\")[1].value = document.getElementById(\"inner_nickname\").value;\n");
      out.write("\t\t\t\tdocument.getElementsByName(\"password\")[1].value = document.getElementById(\"inner_password\").value;\n");
      out.write("\t\t\t\tdocument.getElementsByName(\"idType\")[1].value = \"inner\";\n");
      out.write("\t\t\t\tdocument.forms[\"innerJoinForm\"].submit();\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction innerLogon(){\n");
      out.write("\n");
      out.write("\t\tdocument.forms[\"innerLogonForm\"].submit();\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\t<div>\n");
      out.write("\t\t\t<form method=\"GET\" ACTION=\"/join.do\" id=\"joinForm\">\n");
      out.write("\t\t\t\t<input type = \"hidden\" name = \"email\" value = \"\" >\n");
      out.write("\t\t\t\t<input type = \"hidden\" name = \"nickname\" value = \"\" >\n");
      out.write("\t\t\t\t<input type = \"hidden\" name = \"password\" value = \"\" >\n");
      out.write("\t\t\t\t<input type = \"hidden\" name = \"idType\" value = \"\" >\n");
      out.write("\t\t\t</form>\n");
      out.write("\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
