/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-08-26 01:59:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.StoreEditor;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class gitUploadPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<form method=\"post\" action=\"\">\n");
      out.write("\t\t\t<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta name=\"author\" content=\"\">\n");
      out.write("\n");
      out.write("    <title>Develop - widgetUpload</title>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap Core CSS -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\n");
      out.write("\n");
      out.write("    <!-- Custom CSS -->\n");
      out.write("    <link href=\"css/shop-item.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n");
      out.write("    <!--[if lt IE 9]>\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\n");
      out.write("    <![endif]-->\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/editor.css\" type=\"text/css\" charset=\"utf-8\"/>\n");
      out.write("    <script src=\"js/editor_loader.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <!-- Navigation -->\n");
      out.write("    <nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <!-- Brand and toggle get grouped for better mobile display -->\n");
      out.write("            <div class=\"navbar-header\">\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                </button>\n");
      out.write("                <a class=\"navbar-brand\" href=\"#\">WIDGET STORE</a>\n");
      out.write("            </div>\n");
      out.write("            <!-- Collect the nav links, forms, and other content for toggling -->\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\n");
      out.write("                <ul class=\"nav navbar-nav\">\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\">Develop</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\">Services</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\">Contact</a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <!-- /.navbar-collapse -->\n");
      out.write("        </div>\n");
      out.write("        <!-- /.container -->\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <!-- Page Content -->\n");
      out.write("    <div class=\"container\">\n");
      out.write("\n");
      out.write("        <div class=\"row\">\n");
      out.write("\n");
      out.write("            <div class=\"col-md-3\">\n");
      out.write("                <p class=\"lead\">WidgetStore</p>\n");
      out.write("                <div class=\"list-group\">\n");
      out.write("                    <a href=\"#\" class=\"list-group-item active\">Category 1</a>\n");
      out.write("                    <a href=\"#\" class=\"list-group-item\">Category 2</a>\n");
      out.write("                    <a href=\"#\" class=\"list-group-item\">Category 3</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\t\t\t<!-- ìë¡ë í¼ ìì -->\n");
      out.write("            <div class=\"col-md-9\">\n");
      out.write("\n");
      out.write("                <form id=\"widget-upload\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"modal-body\">\n");
      out.write("\t\t    \t\t\t\t<div id=\"div-lost-msg\">\n");
      out.write("                                <div id=\"icon-lost-msg\" class=\"glyphicon glyphicon-chevron-right\"></div>\n");
      out.write("                                <span id=\"text-lost-msg\">upload git widget.</span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t    \t\t\t\t<input id=\"git-id\" class=\"form-control\" type=\"text\" placeholder=\"Git ID\" required></br>\n");
      out.write("\t\t\t\t\t\t\t<input id=\"repository-name\" class=\"form-control\" type=\"text\" placeholder=\"Repository name\" required></br>\n");
      out.write("\t\t\t\t\t\t\t<input id=\"git-url\" class=\"form-control\" type=\"text\" placeholder=\"Git url\" required></br>\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t<!-- ìëí° ìì -->\n");
      out.write("\t<!--\n");
      out.write("\t\t@decsription\n");
      out.write("\t\të±ë¡íê¸° ìí Formì¼ë¡ ìí©ì ë§ê² ìì íì¬ ì¬ì©íë¤. Form ì´ë¦ì ìëí°ë¥¼ ìì±í  ë ì¤ì ê°ì¼ë¡ ì¤ì íë¤.\n");
      out.write("\t-->\n");
      out.write("\t<form name=\"tx_editor_form\" id=\"tx_editor_form\" action=\"http://posttestserver.com/post.php\" method=\"post\" accept-charset=\"utf-8\">\n");
      out.write("\t\t<!-- ìëí° ì»¨íì´ë ìì -->\n");
      out.write("\t\t<div id=\"tx_trex_container\" class=\"tx-editor-container\">\n");
      out.write("\t\t\t<!-- ì¬ì´ëë° -->\n");
      out.write("\t\t\t<div id=\"tx_sidebar\" class=\"tx-sidebar\">\n");
      out.write("\t\t\t\t<div class=\"tx-sidebar-boundary\">\n");
      out.write("\t\t\t\t\t<!-- ì¬ì´ëë° / ì²¨ë¶ -->\n");
      out.write("\t\t\t\t\t<ul class=\"tx-bar tx-bar-left tx-nav-attach\">\n");
      out.write("\t\t\t\t\t\t<!-- ì´ë¯¸ì§ ì²¨ë¶ ë²í¼ ìì -->\n");
      out.write("\t\t\t\t\t\t<!--\n");
      out.write("\t\t\t\t\t\t\t@decsription\n");
      out.write("\t\t\t\t\t\t\t<li></li> ë¨ìë¡ ìì¹ë¥¼ ì´ëí  ì ìë¤.\n");
      out.write("\t\t\t\t\t\t-->\n");
      out.write("\t\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t\t<div unselectable=\"on\" id=\"tx_image\" class=\"tx-image tx-btn-trans\">\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:;\" title=\"ì¬ì§\" class=\"tx-text\">ì¬ì§</a>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<!-- ì´ë¯¸ì§ ì²¨ë¶ ë²í¼ ë -->\n");
      out.write("\t\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t\t<div unselectable=\"on\" id=\"tx_file\" class=\"tx-file tx-btn-trans\">\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:;\" title=\"íì¼\" class=\"tx-text\">íì¼</a>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t\t<div unselectable=\"on\" id=\"tx_media\" class=\"tx-media tx-btn-trans\">\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:;\" title=\"ì¸ë¶ì»¨íì¸ \" class=\"tx-text\">ì¸ë¶ì»¨íì¸ </a>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<li class=\"tx-list tx-list-extra\">\n");
      out.write("\t\t\t\t\t\t\t<div unselectable=\"on\" class=\"tx-btn-nlrbg tx-extra\">\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"ë²í¼ ëë³´ê¸°\">ë²í¼ ëë³´ê¸°</a>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"tx-extra-menu tx-menu\" style=\"left:-48px;\" unselectable=\"on\">\n");
      out.write("\t\t\t\t\t\t\t\t<!--\n");
      out.write("\t\t\t\t\t\t\t\t\t@decsription\n");
      out.write("\t\t\t\t\t\t\t\t\tì¼ë¶ ë²í¼ë¤ì ë¹¼ì ë ì´ì´ë¡ ì¨ê¸°ë ê¸°ë¥ì ìí  ê²½ì° ì´ ê³³ì¼ë¡ ì´ëìí¬ ì ìë¤.\n");
      out.write("\t\t\t\t\t\t\t\t-->\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t<!-- ì¬ì´ëë° / ì°ì¸¡ìì­ -->\n");
      out.write("\t\t\t\t\t<ul class=\"tx-bar tx-bar-right\">\n");
      out.write("\t\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t\t<div unselectable=\"on\" class=\"tx-btn-lrbg tx-fullscreen\" id=\"tx_fullscreen\">\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"ëê²ì°ê¸° (Ctrl+M)\">ëê²ì°ê¸°</a>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t<ul class=\"tx-bar tx-bar-right tx-nav-opt\">\n");
      out.write("\t\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t\t<div unselectable=\"on\" class=\"tx-switchtoggle\" id=\"tx_switchertoggle\">\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:;\" title=\"ìëí° íì\">ìëí°</a>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<!-- í´ë° - ê¸°ë³¸ ìì -->\n");
      out.write("\t\t\t<!--\n");
      out.write("\t\t\t\t@decsription\n");
      out.write("\t\t\t\tí´ë° ë²í¼ì ê·¸ë£¹íì ë³ê²½ì´ íìí  ëë ìì¹(ì¼ìª½, ê°ì´ë°, ì¤ë¥¸ìª½) ì ë°ë¼ <li> ìëì <div>ì í´ëì¤ëªì ë³ê²½íë©´ ëë¤.\n");
      out.write("\t\t\t\ttx-btn-lbg: ì¼ìª½, tx-btn-bg: ê°ì´ë°, tx-btn-rbg: ì¤ë¥¸ìª½, tx-btn-lrbg: ëë¦½ì ì¸ ê·¸ë£¹\n");
      out.write("\n");
      out.write("\t\t\t\tëë¡­ë¤ì´ ë²í¼ì í¬ê¸°ë¥¼ ë³ê²½íê³ ì í  ê²½ì°ìë ëì´ì ë°ë¼ <li> ìëì <div>ì í´ëì¤ëªì ë³ê²½íë©´ ëë¤.\n");
      out.write("\t\t\t\ttx-slt-70bg, tx-slt-59bg, tx-slt-42bg, tx-btn-43lrbg, tx-btn-52lrbg, tx-btn-57lrbg, tx-btn-71lrbg\n");
      out.write("\t\t\t\ttx-btn-48lbg, tx-btn-48rbg, tx-btn-30lrbg, tx-btn-46lrbg, tx-btn-67lrbg, tx-btn-49lbg, tx-btn-58bg, tx-btn-46bg, tx-btn-49rbg\n");
      out.write("\t\t\t-->\n");
      out.write("\t\t\t<div id=\"tx_toolbar_basic\" class=\"tx-toolbar tx-toolbar-basic\"><div class=\"tx-toolbar-boundary\">\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left\">\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_fontfamily\" unselectable=\"on\" class=\"tx-slt-70bg tx-fontfamily\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" title=\"ê¸ê¼´\">êµ´ë¦¼</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_fontfamily_menu\" class=\"tx-fontfamily-menu tx-menu\" unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left\">\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"tx-slt-42bg tx-fontsize\" id=\"tx_fontsize\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" title=\"ê¸ìí¬ê¸°\">9pt</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_fontsize_menu\" class=\"tx-fontsize-menu tx-menu\" unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left tx-group-font\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-lbg \ttx-bold\" id=\"tx_bold\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"êµµê² (Ctrl+B)\">êµµê²</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-bg \ttx-underline\" id=\"tx_underline\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"ë°ì¤ (Ctrl+U)\">ë°ì¤</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-bg \ttx-italic\" id=\"tx_italic\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"ê¸°ì¸ì (Ctrl+I)\">ê¸°ì¸ì</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-bg \ttx-strike\" id=\"tx_strike\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"ì·¨ìì  (Ctrl+D)\">ì·¨ìì </a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-slt-tbg \ttx-forecolor\" id=\"tx_forecolor\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"ê¸ìì\">ê¸ìì</a>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-arrow\" title=\"ê¸ìì ì í\">ê¸ìì ì í</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_forecolor_menu\" class=\"tx-menu tx-forecolor-menu tx-colorpallete\"\n");
      out.write("\t\t\t\t\t\t\t unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-slt-brbg \ttx-backcolor\" id=\"tx_backcolor\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"ê¸ì ë°°ê²½ì\">ê¸ì ë°°ê²½ì</a>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-arrow\" title=\"ê¸ì ë°°ê²½ì ì í\">ê¸ì ë°°ê²½ì ì í</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_backcolor_menu\" class=\"tx-menu tx-backcolor-menu tx-colorpallete\"\n");
      out.write("\t\t\t\t\t\t\t unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left tx-group-align\">\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-lbg \ttx-alignleft\" id=\"tx_alignleft\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"ì¼ìª½ì ë ¬ (Ctrl+,)\">ì¼ìª½ì ë ¬</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-bg \ttx-aligncenter\" id=\"tx_aligncenter\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"ê°ì´ë°ì ë ¬ (Ctrl+.)\">ê°ì´ë°ì ë ¬</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-bg \ttx-alignright\" id=\"tx_alignright\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"ì¤ë¥¸ìª½ì ë ¬ (Ctrl+/)\">ì¤ë¥¸ìª½ì ë ¬</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-rbg \ttx-alignfull\" id=\"tx_alignfull\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"ììª½ì ë ¬\">ììª½ì ë ¬</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left tx-group-tab\">\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-lbg \ttx-indent\" id=\"tx_indent\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" title=\"ë¤ì¬ì°ê¸° (Tab)\" class=\"tx-icon\">ë¤ì¬ì°ê¸°</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-rbg \ttx-outdent\" id=\"tx_outdent\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" title=\"ë´ì´ì°ê¸° (Shift+Tab)\" class=\"tx-icon\">ë´ì´ì°ê¸°</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left tx-group-list\">\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"tx-slt-31lbg tx-lineheight\" id=\"tx_lineheight\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"ì¤ê°ê²©\">ì¤ê°ê²©</a>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-arrow\" title=\"ì¤ê°ê²©\">ì¤ê°ê²© ì í</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_lineheight_menu\" class=\"tx-lineheight-menu tx-menu\" unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"tx-slt-31rbg tx-styledlist\" id=\"tx_styledlist\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"ë¦¬ì¤í¸\">ë¦¬ì¤í¸</a>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-arrow\" title=\"ë¦¬ì¤í¸\">ë¦¬ì¤í¸ ì í</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_styledlist_menu\" class=\"tx-styledlist-menu tx-menu\" unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left tx-group-etc\">\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-lbg \ttx-emoticon\" id=\"tx_emoticon\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"ì´ëª¨í°ì½\">ì´ëª¨í°ì½</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_emoticon_menu\" class=\"tx-emoticon-menu tx-menu\" unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-bg \ttx-link\" id=\"tx_link\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"ë§í¬ (Ctrl+K)\">ë§í¬</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_link_menu\" class=\"tx-link-menu tx-menu\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-bg \ttx-specialchar\" id=\"tx_specialchar\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"í¹ìë¬¸ì\">í¹ìë¬¸ì</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_specialchar_menu\" class=\"tx-specialchar-menu tx-menu\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-bg \ttx-table\" id=\"tx_table\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"íë§ë¤ê¸°\">íë§ë¤ê¸°</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_table_menu\" class=\"tx-table-menu tx-menu\" unselectable=\"on\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tx-menu-inner\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tx-menu-preview\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tx-menu-rowcol\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tx-menu-deco\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tx-menu-enter\"></div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-rbg \ttx-horizontalrule\" id=\"tx_horizontalrule\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"êµ¬ë¶ì \">êµ¬ë¶ì </a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_horizontalrule_menu\" class=\"tx-horizontalrule-menu tx-menu\" unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left\">\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-lbg \ttx-richtextbox\" id=\"tx_richtextbox\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"ê¸ìì\">ê¸ìì</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_richtextbox_menu\" class=\"tx-richtextbox-menu tx-menu\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tx-menu-header\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tx-menu-preview-area\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"tx-menu-preview\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tx-menu-switch\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"tx-menu-simple tx-selected\"><a><span>ê°ë¨ ì í</span></a></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"tx-menu-advanced\"><a><span>ì§ì  ì í</span></a></div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tx-menu-inner\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tx-menu-footer\">\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"tx-menu-confirm\"\n");
      out.write("\t\t\t\t\t\t\t\t\t src=\"./images/icon/editor/btn_confirm.gif?rv=1.0.1\" alt=\"\"/>\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"tx-menu-cancel\" hspace=\"3\"\n");
      out.write("\t\t\t\t\t\t\t\t\t src=\"./images/icon/editor/btn_cancel.gif?rv=1.0.1\" alt=\"\"/>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-bg \ttx-quote\" id=\"tx_quote\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"ì¸ì©êµ¬ (Ctrl+Q)\">ì¸ì©êµ¬</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_quote_menu\" class=\"tx-quote-menu tx-menu\" unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-bg \ttx-background\" id=\"tx_background\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"ë°°ê²½ì\">ë°°ê²½ì</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_background_menu\" class=\"tx-menu tx-background-menu tx-colorpallete\"\n");
      out.write("\t\t\t\t\t\t\t unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-rbg \ttx-dictionary\" id=\"tx_dictionary\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"ì¬ì \">ì¬ì </a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left tx-group-undo\">\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-lbg \ttx-undo\" id=\"tx_undo\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"ì¤íì·¨ì (Ctrl+Z)\">ì¤íì·¨ì</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"\t\t tx-btn-rbg \ttx-redo\" id=\"tx_redo\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"ë¤ìì¤í (Ctrl+Y)\">ë¤ìì¤í</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-right\">\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"tx-btn-nlrbg tx-advanced\" id=\"tx_advanced\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon\" title=\"í´ë° ëë³´ê¸°\">í´ë° ëë³´ê¸°</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div></div>\n");
      out.write("\t\t\t<!-- í´ë° - ê¸°ë³¸ ë -->\n");
      out.write("\t\t\t<!-- í´ë° - ëë³´ê¸° ìì -->\n");
      out.write("\t\t\t<div id=\"tx_toolbar_advanced\" class=\"tx-toolbar tx-toolbar-advanced\"><div class=\"tx-toolbar-boundary\">\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left\">\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div class=\"tx-tableedit-title\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left tx-group-align\">\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"tx-btn-lbg tx-mergecells\" id=\"tx_mergecells\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon2\" title=\"ë³í©\">ë³í©</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_mergecells_menu\" class=\"tx-mergecells-menu tx-menu\" unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"tx-btn-bg tx-insertcells\" id=\"tx_insertcells\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon2\" title=\"ì½ì\">ì½ì</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_insertcells_menu\" class=\"tx-insertcells-menu tx-menu\" unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div unselectable=\"on\" class=\"tx-btn-rbg tx-deletecells\" id=\"tx_deletecells\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon2\" title=\"ì­ì \">ì­ì </a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_deletecells_menu\" class=\"tx-deletecells-menu tx-menu\" unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left tx-group-align\">\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_cellslinepreview\" unselectable=\"on\" class=\"tx-slt-70lbg tx-cellslinepreview\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" title=\"ì  ë¯¸ë¦¬ë³´ê¸°\"></a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_cellslinepreview_menu\" class=\"tx-cellslinepreview-menu tx-menu\"\n");
      out.write("\t\t\t\t\t\t\t unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_cellslinecolor\" unselectable=\"on\" class=\"tx-slt-tbg tx-cellslinecolor\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon2\" title=\"ì ì\">ì ì</a>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tx-colorpallete\" unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_cellslinecolor_menu\" class=\"tx-cellslinecolor-menu tx-menu tx-colorpallete\"\n");
      out.write("\t\t\t\t\t\t\t unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_cellslineheight\" unselectable=\"on\" class=\"tx-btn-bg tx-cellslineheight\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon2\" title=\"ëê»\">ëê»</a>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_cellslineheight_menu\" class=\"tx-cellslineheight-menu tx-menu\"\n");
      out.write("\t\t\t\t\t\t\t unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_cellslinestyle\" unselectable=\"on\" class=\"tx-btn-bg tx-cellslinestyle\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon2\" title=\"ì¤íì¼\">ì¤íì¼</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_cellslinestyle_menu\" class=\"tx-cellslinestyle-menu tx-menu\" unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_cellsoutline\" unselectable=\"on\" class=\"tx-btn-rbg tx-cellsoutline\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon2\" title=\"íëë¦¬\">íëë¦¬</a>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_cellsoutline_menu\" class=\"tx-cellsoutline-menu tx-menu\" unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left\">\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_tablebackcolor\" unselectable=\"on\" class=\"tx-btn-lrbg tx-tablebackcolor\"\n");
      out.write("\t\t\t\t\t\t\t style=\"background-color:#9aa5ea;\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon2\" title=\"íì´ë¸ ë°°ê²½ì\">íì´ë¸ ë°°ê²½ì</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_tablebackcolor_menu\" class=\"tx-tablebackcolor-menu tx-menu tx-colorpallete\"\n");
      out.write("\t\t\t\t\t\t\t unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<ul class=\"tx-bar tx-bar-left\">\n");
      out.write("\t\t\t\t\t<li class=\"tx-list\">\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_tabletemplate\" unselectable=\"on\" class=\"tx-btn-lrbg tx-tabletemplate\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"tx-icon2\" title=\"íì´ë¸ ìì\">íì´ë¸ ìì</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"tx_tabletemplate_menu\" class=\"tx-tabletemplate-menu tx-menu tx-colorpallete\"\n");
      out.write("\t\t\t\t\t\t\t unselectable=\"on\"></div>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t\t</div></div>\n");
      out.write("\t\t\t<!-- í´ë° - ëë³´ê¸° ë -->\n");
      out.write("\t\t\t<!-- í¸ì§ìì­ ìì -->\n");
      out.write("\t\t\t\t<!-- ìëí° Start -->\n");
      out.write("\t<div id=\"tx_canvas\" class=\"tx-canvas\">\n");
      out.write("\t\t<div id=\"tx_loading\" class=\"tx-loading\"><div><img src=\"images/icon/editor/loading2.png\" width=\"113\" height=\"21\" align=\"absmiddle\"/></div></div>\n");
      out.write("\t\t<div id=\"tx_canvas_wysiwyg_holder\" class=\"tx-holder\" style=\"display:block;\">\n");
      out.write("\t\t\t<iframe id=\"tx_canvas_wysiwyg\" name=\"tx_canvas_wysiwyg\" allowtransparency=\"true\" frameborder=\"0\"></iframe>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"tx-source-deco\">\n");
      out.write("\t\t\t<div id=\"tx_canvas_source_holder\" class=\"tx-holder\">\n");
      out.write("\t\t\t\t<textarea id=\"tx_canvas_source\" rows=\"30\" cols=\"30\"></textarea>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div id=\"tx_canvas_text_holder\" class=\"tx-holder\">\n");
      out.write("\t\t\t<textarea id=\"tx_canvas_text\" rows=\"30\" cols=\"30\"></textarea>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t\t\t\t\t<!-- ëì´ì¡°ì  Start -->\n");
      out.write("\t<div id=\"tx_resizer\" class=\"tx-resize-bar\">\n");
      out.write("\t\t<div class=\"tx-resize-bar-bg\"></div>\n");
      out.write("\t\t<img id=\"tx_resize_holder\" src=\"images/icon/editor/skin/01/btn_drag01.gif\" width=\"58\" height=\"12\" unselectable=\"on\" alt=\"\" />\n");
      out.write("\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"tx-side-bi\" id=\"tx_side_bi\">\n");
      out.write("\t\t<div style=\"text-align: right;\">\n");
      out.write("\t\t\t<img hspace=\"4\" height=\"14\" width=\"78\" align=\"absmiddle\" src=\"images/icon/editor/editor_bi.png\" />\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t\t\t\t<!-- í¸ì§ìì­ ë -->\n");
      out.write("\t\t\t<!-- ì²¨ë¶ë°ì¤ ìì -->\n");
      out.write("\t\t\t\t<!-- íì¼ì²¨ë¶ë°ì¤ Start -->\n");
      out.write("\t<div id=\"tx_attach_div\" class=\"tx-attach-div\">\n");
      out.write("\t\t<div id=\"tx_attach_txt\" class=\"tx-attach-txt\">íì¼ ì²¨ë¶</div>\n");
      out.write("\t\t<div id=\"tx_attach_box\" class=\"tx-attach-box\">\n");
      out.write("\t\t\t<div class=\"tx-attach-box-inner\">\n");
      out.write("\t\t\t\t<div id=\"tx_attach_preview\" class=\"tx-attach-preview\"><p></p><img src=\"images/icon/editor/pn_preview.gif\" width=\"147\" height=\"108\" unselectable=\"on\"/></div>\n");
      out.write("\t\t\t\t<div class=\"tx-attach-main\">\n");
      out.write("\t\t\t\t\t<div id=\"tx_upload_progress\" class=\"tx-upload-progress\"><div>0%</div><p>íì¼ì ìë¡ëíë ì¤ìëë¤.</p></div>\n");
      out.write("\t\t\t\t\t<ul class=\"tx-attach-top\">\n");
      out.write("\t\t\t\t\t\t<li id=\"tx_attach_delete\" class=\"tx-attach-delete\"><a>ì ì²´ì­ì </a></li>\n");
      out.write("\t\t\t\t\t\t<li id=\"tx_attach_size\" class=\"tx-attach-size\">\n");
      out.write("\t\t\t\t\t\t\tíì¼: <span id=\"tx_attach_up_size\" class=\"tx-attach-size-up\"></span>/<span id=\"tx_attach_max_size\"></span>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<li id=\"tx_attach_tools\" class=\"tx-attach-tools\">\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t<ul id=\"tx_attach_list\" class=\"tx-attach-list\"></ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t\t\t\t<!-- ì²¨ë¶ë°ì¤ ë -->\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- ìëí° ì»¨íì´ë ë -->\n");
      out.write("\t</form>\n");
      out.write("</div>\n");
      out.write("<!-- ìëí° ë -->\n");
      out.write("\t\t\t\t\t<div class=\"dropdown\">\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-default dropdown-toggle\" type=\"button\" id=\"dropdownMenu1\" data-toggle=\"dropdown\" aria-expanded=\"true\">\n");
      out.write("\t\t\t\t\t\t\tì¹´íê³ ë¦¬\n");
      out.write("\t\t\t\t\t\t\t<span class=\"caret\"></span>\n");
      out.write("\t\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu\" role=\"menu\" aria-labelledby=\"dropdownMenu1\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<li role=\"presentation\"><a role=\"menuitem\" tabindex=\"-1\" href=\"#\">ì¢ë¥1</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li role=\"presentation\"><a role=\"menuitem\" tabindex=\"-1\" href=\"#\">ì¢ë¥2</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li role=\"presentation\"><a role=\"menuitem\" tabindex=\"-1\" href=\"#\">ì¢ë¥3</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t<li role=\"presentation\"><a role=\"menuitem\" tabindex=\"-1\" href=\"#\">ì¢ë¥4</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t</div></br>\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-footer\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"alert alert-warning\" role=\"alert\">\n");
      out.write("\t\t\t\t\t\t\t\t1.ì£¼ìì¬í­1</br>\n");
      out.write("\t\t\t\t\t\t\t\t2.ì£¼ìì¬í­2</br>\n");
      out.write("\t\t\t\t\t\t\t\t3.ì£¼ìì¬í­3\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t    \t\t    <div class=\"modal-footer\">\n");
      out.write("                            <div>\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-primary btn-lg btn-block\">Upload</button>\n");
      out.write("                            </div>\n");
      out.write("\t\t    \t\t    </div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("    <!-- /.container -->\n");
      out.write("\n");
      out.write("    <div class=\"container\">\n");
      out.write("\n");
      out.write("        <hr>\n");
      out.write("\n");
      out.write("        <!-- Footer -->\n");
      out.write("        <footer>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-12\">\n");
      out.write("                    <p>Copyright &copy; Your Website 2014</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </footer>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("    <!-- /.container -->\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\tvar config = {\n");
      out.write("\t\ttxHost: '', /* ë°íì ì ë¦¬ìì¤ë¤ì ë¡ë©í  ë íìí ë¶ë¶ì¼ë¡, ê²½ë¡ê° ë³ê²½ëë©´ ì´ ë¶ë¶ ìì ì´ íì. ex) http://xxx.xxx.com */\n");
      out.write("\t\ttxPath: '', /* ë°íì ì ë¦¬ìì¤ë¤ì ë¡ë©í  ë íìí ë¶ë¶ì¼ë¡, ê²½ë¡ê° ë³ê²½ëë©´ ì´ ë¶ë¶ ìì ì´ íì. ex) /xxx/xxx/ */\n");
      out.write("\t\ttxService: 'sample', /* ìì íììì. */\n");
      out.write("\t\ttxProject: 'sample', /* ìì íììì. íë¡ì í¸ê° ì¬ë¬ê°ì¼ ê²½ì°ë§ ìì íë¤. */\n");
      out.write("\t\tinitializedId: \"\", /* ëë¶ë¶ì ê²½ì°ì ë¹ë¬¸ìì´ */\n");
      out.write("\t\twrapper: \"tx_trex_container\", /* ìëí°ë¥¼ ëë¬ì¸ê³  ìë ë ì´ì´ ì´ë¦(ìëí° ì»¨íì´ë) */\n");
      out.write("\t\tform: 'tx_editor_form'+\"\", /* ë±ë¡íê¸° ìí Form ì´ë¦ */\n");
      out.write("\t\ttxIconPath: \"images/icon/editor/\", /*ìëí°ì ì¬ì©ëë ì´ë¯¸ì§ ëë í°ë¦¬, íìì ë°ë¼ ìì íë¤. */\n");
      out.write("\t\ttxDecoPath: \"images/deco/contents/\", /*ë³¸ë¬¸ì ì¬ì©ëë ì´ë¯¸ì§ ëë í°ë¦¬, ìë¹ì¤ìì ì¬ì©í  ëë ìì±ë ì»¨íì¸ ë¡ ë°°í¬ëê¸° ìí´ ì ëê²½ë¡ë¡ ìì íë¤. */\n");
      out.write("\t\tcanvas: {\n");
      out.write("            exitEditor:{\n");
      out.write("                /*\n");
      out.write("                desc:'ë¹ ì ¸ ëì¤ìë ¤ë©´ shift+bë¥¼ ëë¥´ì¸ì.',\n");
      out.write("                hotKey: {\n");
      out.write("                    shiftKey:true,\n");
      out.write("                    keyCode:66\n");
      out.write("                },\n");
      out.write("                nextElement: document.getElementsByTagName('button')[0]\n");
      out.write("                */\n");
      out.write("            },\n");
      out.write("\t\t\tstyles: {\n");
      out.write("\t\t\t\tcolor: \"#123456\", /* ê¸°ë³¸ ê¸ìì */\n");
      out.write("\t\t\t\tfontFamily: \"êµ´ë¦¼\", /* ê¸°ë³¸ ê¸ìì²´ */\n");
      out.write("\t\t\t\tfontSize: \"10pt\", /* ê¸°ë³¸ ê¸ìí¬ê¸° */\n");
      out.write("\t\t\t\tbackgroundColor: \"#fff\", /*ê¸°ë³¸ ë°°ê²½ì */\n");
      out.write("\t\t\t\tlineHeight: \"1.5\", /*ê¸°ë³¸ ì¤ê°ê²© */\n");
      out.write("\t\t\t\tpadding: \"8px\" /* ìì§ì ìì­ì ì¬ë°± */\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\tshowGuideArea: false\n");
      out.write("\t\t},\n");
      out.write("\t\tevents: {\n");
      out.write("\t\t\tpreventUnload: false\n");
      out.write("\t\t},\n");
      out.write("\t\tsidebar: {\n");
      out.write("\t\t\tattachbox: {\n");
      out.write("\t\t\t\tshow: true,\n");
      out.write("\t\t\t\tconfirmForDeleteAll: true\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\tattacher: {\n");
      out.write("\t\t\t\timage : {\n");
      out.write("\t\t\t\t\t\tpopPageUrl : \"/StoreEditor/pages/trex/image.jsp\"\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\tfile : {\n");
      out.write("\t\t\t\t\tpopPageUrl : \"/StoreEditor/pages/trex/file.jsp\"\n");
      out.write("\t\t\t\t}\t\t\t\t\n");
      out.write("\t\t\t}\n");
      out.write("\t\t},\n");
      out.write("\t\tsize: {\n");
      out.write("\t\t\tcontentWidth: 700 /* ì§ì ë ë³¸ë¬¸ìì­ì ëì´ê° ìì ê²½ì°ì ì¤ì  */\n");
      out.write("\t\t}\n");
      out.write("\t};\n");
      out.write("\n");
      out.write("\tEditorJSLoader.ready(function(Editor) {\n");
      out.write("\t\tvar editor = new Editor(config);\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<!-- Sample: Saving Contents -->\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t/* ìì ì© í¨ì */\n");
      out.write("\tfunction saveContent() {\n");
      out.write("\t\tEditor.save(); // ì´ í¨ìë¥¼ í¸ì¶íì¬ ê¸ì ë±ë¡íë©´ ëë¤.\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\t/**\n");
      out.write("\t * Editor.save()ë¥¼ í¸ì¶í ê²½ì° ë°ì´í°ê° ì í¨íì§ ê²ì¬íê¸° ìí´ ë¶ë¥´ë ì½ë°±í¨ìë¡\n");
      out.write("\t * ìí©ì ë§ê² ìì íì¬ ì¬ì©íë¤.\n");
      out.write("\t * ëª¨ë  ë°ì´í°ê° ì í¨í  ê²½ì°ì trueë¥¼ ë¦¬í´íë¤.\n");
      out.write("\t * @function\n");
      out.write("\t * @param {Object} editor - ìëí°ìì ëê²¨ì£¼ë editor ê°ì²´\n");
      out.write("\t * @returns {Boolean} ëª¨ë  ë°ì´í°ê° ì í¨í  ê²½ì°ì true\n");
      out.write("\t */\n");
      out.write("\tfunction validForm(editor) {\n");
      out.write("\t\t// Place your validation logic here\n");
      out.write("\n");
      out.write("\t\t// sample : validate that content exists\n");
      out.write("\t\tvar validator = new Trex.Validator();\n");
      out.write("\t\tvar content = editor.getContent();\n");
      out.write("\t\tif (!validator.exists(content)) {\n");
      out.write("\t\t\talert('ë´ì©ì ìë ¥íì¸ì');\n");
      out.write("\t\t\treturn false;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\treturn true;\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\t/**\n");
      out.write("\t * Editor.save()ë¥¼ í¸ì¶í ê²½ì° validForm callback ì´ ìíë ì´í\n");
      out.write("\t * ì¤ì  form submitì ìí´ form íëë¥¼ ìì±, ë³ê²½íê¸° ìí´ ë¶ë¥´ë ì½ë°±í¨ìë¡\n");
      out.write("\t * ê°ì ìí©ì ë§ê² ì ì í ìì©íì¬ ì¬ì©íë¤.\n");
      out.write("\t * @function\n");
      out.write("\t * @param {Object} editor - ìëí°ìì ëê²¨ì£¼ë editor ê°ì²´\n");
      out.write("\t * @returns {Boolean} ì ìì ì¸ ê²½ì°ì true\n");
      out.write("\t */\n");
      out.write("\tfunction setForm(editor) {\n");
      out.write("        var i, input;\n");
      out.write("        var form = editor.getForm();\n");
      out.write("        var content = editor.getContent();\n");
      out.write("\n");
      out.write("        // ë³¸ë¬¸ ë´ì©ì íëë¥¼ ìì±íì¬ ê°ì í ë¹íë ë¶ë¶\n");
      out.write("        var textarea = document.createElement('textarea');\n");
      out.write("        textarea.name = 'content';\n");
      out.write("        textarea.value = content;\n");
      out.write("        form.createField(textarea);\n");
      out.write("\n");
      out.write("        /* ìëì ì½ëë ì²¨ë¶ë ë°ì´í°ë¥¼ íëë¥¼ ìì±íì¬ ê°ì í ë¹íë ë¶ë¶ì¼ë¡ ìí©ì ë§ê² ìì íì¬ ì¬ì©íë¤.\n");
      out.write("         ì²¨ë¶ë ë°ì´í° ì¤ì ì£¼ì´ì§ ì¢ë¥(image,file..)ì í´ë¹íë ê²ë§ ë°°ì´ë¡ ëê²¨ì¤ë¤. */\n");
      out.write("        var images = editor.getAttachments('image');\n");
      out.write("        for (i = 0; i < images.length; i++) {\n");
      out.write("            // existStageë íì¬ ë³¸ë¬¸ì ì¡´ì¬íëì§ ì¬ë¶\n");
      out.write("            if (images[i].existStage) {\n");
      out.write("                // dataë íììì execAttach ë±ì íµí´ ëê¸´ ë°ì´í°\n");
      out.write("                alert('attachment information - image[' + i + '] \\r\\n' + JSON.stringify(images[i].data));\n");
      out.write("                input = document.createElement('input');\n");
      out.write("                input.type = 'hidden';\n");
      out.write("                input.name = 'attach_image';\n");
      out.write("                input.value = images[i].data.imageurl;  // ìììë ì´ë¯¸ì§ê²½ë¡ë§ ë°ìì ì¬ì©\n");
      out.write("                form.createField(input);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        var files = editor.getAttachments('file');\n");
      out.write("        for (i = 0; i < files.length; i++) {\n");
      out.write("            input = document.createElement('input');\n");
      out.write("            input.type = 'hidden';\n");
      out.write("            input.name = 'attach_file';\n");
      out.write("            input.value = files[i].data.attachurl;\n");
      out.write("            form.createField(input);\n");
      out.write("        }\n");
      out.write("        return true;\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("<div><button onclick='saveContent()'>SAMPLE - submit contents</button></div>\n");
      out.write("<!-- End: Saving Contents -->\n");
      out.write("\n");
      out.write("<!-- Sample: Loading Contents -->\n");
      out.write("<textarea id=\"sample_contents_source\" style=\"display:none;\">\n");
      out.write("\t<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\n");
      out.write("\t<p style=\"text-align: center;\">\n");
      out.write("\t\t<img src=\"http://cfile273.uf.daum.net/image/2064CD374EE1ACCB0F15C8\" class=\"tx-daum-image\" style=\"clear: none; float: none;\"/>\n");
      out.write("\t</p>ï»¿\n");
      out.write("\t<p>\n");
      out.write("\t\t<a href=\"http://cfile297.uf.daum.net/attach/207C8C1B4AA4F5DC01A644\"><img src=\"snapshot/images/icon/p_gif_s.gif\"/> editor_bi.gif</a>\n");
      out.write("\t</p>\n");
      out.write("</textarea>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tfunction loadContent() {\n");
      out.write("\t\tvar attachments = {};\n");
      out.write("\t\tattachments['image'] = [];\n");
      out.write("\t\tattachments['image'].push({\n");
      out.write("\t\t\t'attacher': 'image',\n");
      out.write("\t\t\t'data': {\n");
      out.write("\t\t\t\t'imageurl': 'http://cfile273.uf.daum.net/image/2064CD374EE1ACCB0F15C8',\n");
      out.write("\t\t\t\t'filename': 'github.gif',\n");
      out.write("\t\t\t\t'filesize': 59501,\n");
      out.write("\t\t\t\t'originalurl': 'http://cfile273.uf.daum.net/original/2064CD374EE1ACCB0F15C8',\n");
      out.write("\t\t\t\t'thumburl': 'http://cfile273.uf.daum.net/P150x100/2064CD374EE1ACCB0F15C8'\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t\tattachments['file'] = [];\n");
      out.write("\t\tattachments['file'].push({\n");
      out.write("\t\t\t'attacher': 'file',\n");
      out.write("\t\t\t'data': {\n");
      out.write("\t\t\t\t'attachurl': 'http://cfile297.uf.daum.net/attach/207C8C1B4AA4F5DC01A644',\n");
      out.write("\t\t\t\t'filemime': 'image/gif',\n");
      out.write("\t\t\t\t'filename': 'editor_bi.gif',\n");
      out.write("\t\t\t\t'filesize': 640\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t\t/* ì ì¥ë ì»¨íì¸ ë¥¼ ë¶ë¬ì¤ê¸° ìí í¨ì í¸ì¶ */\n");
      out.write("\t\tEditor.modify({\n");
      out.write("\t\t\t\"attachments\": function () { /* ì ì¥ë ì²¨ë¶ê° ìì ê²½ì° ë°°ì´ë¡ ëê¹, ìì ë¶ë¶ì ìì íê³  ìë ë¶ë¶ì ìì ìì´ ì¬ì© */\n");
      out.write("\t\t\t\tvar allattachments = [];\n");
      out.write("\t\t\t\tfor (var i in attachments) {\n");
      out.write("\t\t\t\t\tallattachments = allattachments.concat(attachments[i]);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\treturn allattachments;\n");
      out.write("\t\t\t}(),\n");
      out.write("\t\t\t\"content\": document.getElementById(\"sample_contents_source\") /* ë´ì© ë¬¸ìì´, ì£¼ì´ì§ íë(textarea) ìë¦¬ë¨¼í¸ */\n");
      out.write("\t\t});\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("<div><button onclick='loadContent()'>SAMPLE - load contents to editor</button></div>\n");
      out.write("    <!-- jQuery -->\n");
      out.write("    <script src=\"js/jquery.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap Core JavaScript -->\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- End: Loading Contents -->\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("        </form>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
