/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-05-23 15:34:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.logonPage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class entryPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html class=\"full\" lang=\"ko\">\n");
      out.write("<!-- Make sure the <html> tag is set to the .full CSS class. Change the background image in the full.css file. -->\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta name=\"author\" content=\"\">\n");
      out.write("\n");
      out.write("    <title>The Big Picture - Start Bootstrap Template</title>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <!-- Bootstrap Core CSS -->\n");
      out.write("    <link href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7\" crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("    <!-- Custom CSS -->\n");
      out.write("    <link href=\"/css/the-big-picture.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n");
      out.write("    <!--[if lt IE 9]>\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\n");
      out.write("    <![endif]-->\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <!-- Navigation -->\n");
      out.write("    <nav class=\"navbar navbar-inverse navbar-fixed-bottom\" role=\"navigation\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <!-- Brand and toggle get grouped for better mobile display -->\n");
      out.write("            <div class=\"navbar-header\">\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                </button>\n");
      out.write("                <a class=\"navbar-brand\" href=\"#\">Start Bootstrap</a>\n");
      out.write("            </div>\n");
      out.write("            <!-- Collect the nav links, forms, and other content for toggling -->\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\n");
      out.write("                <ul class=\"nav navbar-nav\">\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\">About</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\">Services</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\">Contact</a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <!-- /.navbar-collapse -->\n");
      out.write("        </div>\n");
      out.write("        <!-- /.container -->\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <!-- Page Content -->\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-md-6 col-sm-12\">\n");
      out.write("           \n");
      out.write("\t\t\n");
      out.write("                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni, iusto, unde, sunt incidunt id sapiente rerum soluta voluptate harum veniam fuga odit ea pariatur vel eaque sint sequi tenetur eligendi.</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- /.row -->\n");
      out.write("    </div>\n");
      out.write("    <!-- /.container -->\n");
      out.write("\n");
      out.write("    <script type=\"text/javascript\" charset=\"utf-8\" src=\"http://code.jquery.com/jquery-2.2.3.min.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" charset=\"utf-8\" src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.0/jquery.cookie.min.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" charset=\"utf-8\" src=\"https://static.nid.naver.com/js/naverLogin_implicit-1.0.2.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap Core JavaScript -->\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("\t\tvar mail;\n");
      out.write("\t\tvar nick;\n");
      out.write("\n");
      out.write("\t\tvar naver = new naver_id_login(\"Vf8cYbYQv2N0c_cSv_XA\", \"http://114.129.211.33:8181/\");\n");
      out.write("\t\tvar state = naver.getUniqState();\n");
      out.write("\t\tnaver.setState(state);\n");
      out.write("\t\tnaver.setButton(BUTTON_COLOR_GREEN, BANNER_BIG_TYPE, 40);\n");
      out.write("\t\tnaver.setStateStore();\n");
      out.write("\t\tnaver.init_naver_id_login();\t \n");
      out.write("\n");
      out.write("\t\tgetParameter = function(param){\n");
      out.write("\t\t    full_url=location.href;\n");
      out.write("\t\t    \n");
      out.write("\t\t  \t\t\t//íë¼ë¯¸í°ê° íëë ììë\n");
      out.write("\t\t    if(full_url.search(\"&\") == -1)\n");
      out.write("\t\t        return false;\n");
      out.write("\n");
      out.write("\t\t  \t\t\tif(full_url.indexOf(\"#\") != -1)\n");
      out.write("\t\t    \t\t\t\tsearch=full_url.split(\"#\");\n");
      out.write("\t\t  \t\t\telse if(full_url.indexOf(\"?\") != -1)\n");
      out.write("\t\t  \t\t\t\t\tsearch=full_url.split(\"?\");\n");
      out.write("\t\t  \t\t\telse\n");
      out.write("\t\t  \t\t\t\t\treturn null;\n");
      out.write("\t\t  \t\t\t\n");
      out.write("\t\t\t\t    //í´ë¹íë íë¼ë¯¸í°ê° ììë.\n");
      out.write("\t\t    if(search[1].indexOf(param)==(-1)){\n");
      out.write("\t\t        \n");
      out.write("\t\t        return \"\";\n");
      out.write("\t\t        return;\n");
      out.write("\t\t\t\t    }\n");
      out.write("\t\t    \n");
      out.write("\t\t    search=search[1].split(\"&\");\n");
      out.write("\n");
      out.write("\t\t   \t\t //íê°ì íë¼ë¯¸í°ì¼ë.\n");
      out.write("\t\t    if(search.length<3){\n");
      out.write("\t\t       \n");
      out.write("\t\t        data=search[1].split(\"=\");\n");
      out.write("\t\t        return data[1];\n");
      out.write("\t\t\t\t    }\n");
      out.write("\t\t    else{\n");
      out.write("\t\t\t\t    //ì¬ë¬ê°ì íë¼ë¯¸í° ì¼ë.\n");
      out.write("\t\t\t    var i=0;\n");
      out.write("\t\t    \t\tfor(i=0 ; i < search.length ; i++){\n");
      out.write("\t\t    \t\t\t\tdata = search[i].split(\"=\");\n");
      out.write("\t\t\t    \t\t\tif(data[0].match(param))\n");
      out.write("\t\t\t    \t\t\t\treturn data[1];\n");
      out.write("\t\t    \t\t\t}\n");
      out.write("\t\t\t    \tif(i==search.length)\n");
      out.write("\t\t    \t\t\t\treturn NULL;\n");
      out.write("\t\t    \t\t}\n");
      out.write("\t\t    \n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tfunction setHiddenForm(){\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tmail = naver.getProfileData('email');\n");
      out.write("\t\t\tnick = naver.getProfileData('nickname');\n");
      out.write("\t\t\tdocument.getElementsByName(\"email\")[0].value = mail;\n");
      out.write("\t\t\tdocument.getElementsByName(\"nickname\")[0].value = nick;\n");
      out.write("\t\t\tdocument.getElementsByName(\"password\")[0].value = \"\";\n");
      out.write("\t\t\tdocument.getElementsByName(\"reg_date\")[0].value = \"\";\n");
      out.write("\t\t\tdocument.getElementsByName(\"idType\")[0].value = \"naver\";\n");
      out.write("\t\t\tconsole.log(\"ë¤ì´ë² íë¡í ë³´ë´ê¸° : \" + mail + \" , \" + nick);\n");
      out.write("\t\t\tdocument.forms[\"hiddenForm\"].submit();\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\twindow.onload=function(){\n");
      out.write("\t\t\tconsole.log(pageContext.request.contextPath);\n");
      out.write("\t\t\n");
      out.write("\t\t\t");

			/*  logonBeanì¼ë¡ ë¶í° ëì´ì¨ ê°ì ì½ì´ ë¡ê·¸ì¸ ì±ê³µì´ ë ê²½ì° ë¡ê·¸ì¸ì ì§ë¥¼ ìí´ ì¸ìì ë³ëì ê°ì ì ì¥íë¤. */
			
				try{
				   
					if( session.getAttribute("id") != null)
						response.sendRedirect("/main.do");
					
					if( (request.getAttribute("oauthJoin")!= null || request.getAttribute("innerJoin") != null) )	{
						
      out.write("\n");
      out.write("\t\t\t\t\t\t\talert( ");
      out.print( (String)request.getAttribute("message") );
      out.write(" );\n");
      out.write("\t\t\t\t\t\t");

						
						session.setAttribute("id", "naverLogin");
						response.sendRedirect("/main.do");

				}else{
					
      out.write("\n");
      out.write("\t\t\t//ë¤ì´ë²ë¡ê·¸ì¸ ì½ë°±ì¸ì§ íì¸ \n");
      out.write("\t\t\t\t\t\tvar state = getParameter(\"state\");\n");
      out.write("\t\t\t\t\t\tif(state == null)\n");
      out.write("\t\t\t\t\t\t\tconsole.log(\"error of urlpaser\");\n");
      out.write("\t\t\t\t\t\tvar savedNaverState = naver.state;\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\tif( state.match(savedNaverState) ){\n");
      out.write("\t\t\t\t\t\t\t\tnaver.get_naver_userprofile(\"setHiddenForm()\");\t\t\t\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t");

				}//else
			}//try
			catch(Exception e){
				e.printStackTrace();}
					
			
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\t\t<!-- <input type=\"BUTTON\" name=\"innerJoin\" value=\"ê°ìíê¸° \" onClick=\"innerJoin()\"><br>\n");
      out.write("\t\t<input type=\"BUTTON\" name=\"innerLogon\" value=\"ë¡ê·¸ì¸íê¸° \" onClick=\"innerLogon()\">ë¡ê·¸ì¸íê¸° \n");
      out.write("\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<form method=\"GET\" ACTION=\"/logon.do\" id=\"hiddenForm\">\n");
      out.write("\t\t\t<input type = \"hidden\" name = \"kind\" value = \"inner_logon\" >\n");
      out.write("\t\t\t<input type=\"TEXT\" name=\"input_text\" value=\"ìì´ë\">\n");
      out.write("\t\t\t<input type=\"TEXT\" name=\"input_pw\">\n");
      out.write("\t</form></div>\n");
      out.write("\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<form method=\"GET\" ACTION=\"/join.do\" id=\"hiddenForm\">\n");
      out.write("\t\t\t\t<input type = \"hidden\" name = \"email\" value = \"\" >\n");
      out.write("\t\t\t\t<input type = \"hidden\" name = \"nickname\" value = \"\" >\n");
      out.write("\t\t\t\t<input type = \"hidden\" name = \"password\" value = \"\" >\n");
      out.write("\t\t\t\t<input type = \"hidden\" name = \"idType\" value = \"\" >\n");
      out.write("\t\t\t\t<input type = \"hidden\" name = \"reg_date\" value = \"\" >\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div> -->\n");
      out.write("\t\t\n");
      out.write("\t\t<script>\n");
      out.write("\t\t\n");
      out.write("\t\t\tfunction innerJoin(){\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t\tlocation.href = \"/innerJoin.do\";\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
