/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-09-05 14:23:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta name=\"author\" content=\"\">\n");
      out.write("\n");
      out.write("    <title>Widget Store - OSS</title>\n");
      out.write("    \n");
      out.write("<link rel=\"stylesheet\" href=\"http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css\" />\n");
      out.write("<script language=\"Javascript\" type=\"text/javascript\" src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\n");
      out.write("<script language=\"Javascript\" type=\"text/javascript\" src=\"http://code.jquery.com/ui/1.10.3/jquery-ui.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap Core CSS -->\n");
      out.write("    <link href=\"WidgetClientPage/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- Custom CSS -->\n");
      out.write("    <link href=\"WidgetClientPage/css/stylish-portfolio.css\" rel=\"stylesheet\">\n");
      out.write("\t<!-- bootsnipp down -->\n");
      out.write("\t<link href=\"WidgetClientPage/css/login.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- Custom Fonts -->\n");
      out.write("    <link href=\"WidgetClientPage/font-awesome/font-awesome.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("    <link href=\"http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n");
      out.write("    <!--[if lt IE 9]>\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\n");
      out.write("    <![endif]-->\n");
      out.write("\t<style>\n");
      out.write("\t#qTip {\n");
      out.write("\t\tpadding: 3px;\n");
      out.write("\t\tborder: 1px solid #666;\n");
      out.write("\t\tdisplay: none;\n");
      out.write("\t\tbackground: #999;\n");
      out.write("\t\tcolor: #FFF;\n");
      out.write("\t\tfont: bold 11px Verdana, Arial, Helvetica, sans-serif;\n");
      out.write("\t\ttext-align: left;\n");
      out.write("\t\tposition: absolute;\n");
      out.write("\t\tz-index: 99999;\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\ti {\n");
      out.write("\t\tfont-style: normal;\n");
      out.write("\t\ttext-decoration: underline;\n");
      out.write("\t}\n");
      out.write("\t</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <!-- Navigation -->\n");
      out.write("    <a id=\"menu-toggle\" href=\"#\" class=\"btn btn-dark btn-md toggle\"><i class=\"fa fa-th-large\"></i></a>\n");
      out.write("    <nav id=\"sidebar-wrapper\">\n");
      out.write("        <ul class=\"sidebar-nav\">\n");
      out.write("            <a id=\"menu-close\" href=\"#\" class=\"btn btn-light btn-md pull-right toggle\"><i class=\"fa fa-times\"></i></a>\n");
      out.write("            <li class=\"sidebar-brand\">\n");
      out.write("                <a href=\"#top\"  onclick = $(\"#menu-close\").click(); >Widget Store</a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#Sign In\" id=\"signIn\" style=\"display:''\" onclick = $(\"#menu-close\").click(); data-toggle=\"modal\" data-target=\"#login-modal\">Sign in</a>\n");
      out.write("            </li>\n");
      out.write("\t\t\t<li>\n");
      out.write("                <a href=\"#Sign Out\" id=\"signOut\" style=\"display:none;\" onclick =\"fun_signOut()\" >Sign out</a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"Store.jsp\" onclick =\"fun_Store()\"; >Store</a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#Custom\" onclick = $(\"#menu-close\").click(); data-toggle=\"modal\" data-target=\"#Register-edit-modal\">Custom</a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#Setting\" onclick = $(\"#menu-close\").click(); >Setting</a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#About\" onclick = $(\"#menu-close\").click(); >About</a>\n");
      out.write("            </li>\n");
      out.write("        </ul>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("\t<!-- BEGIN # MODAL LOGIN -->\n");
      out.write("\t<div class=\"modal fade\" id=\"login-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\" style=\"display: none;\">\n");
      out.write("    \t<div class=\"modal-dialog\">\n");
      out.write("\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t<div class=\"modal-header\" align=\"center\">\n");
      out.write("\t\t\t\t\t<img class=\"img-circle\" id=\"img_logo\" src=\"WidgetClientPage/img/test1.jpg\">\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("\t\t\t\t\t\t<span class=\"glyphicon glyphicon-remove\" aria-hidden=\"true\"></span>\n");
      out.write("\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("                \n");
      out.write("                <!-- Begin # DIV Form -->\n");
      out.write("                <div id=\"div-forms\">\n");
      out.write("                \n");
      out.write("                    <!-- Begin # Login Form -->\n");
      out.write("                    <form id=\"login-form\" method=\"POST\" ACTION=\"login.do\" >\n");
      out.write("\t\t                <div class=\"modal-body\">\n");
      out.write("\t\t\t\t    \t\t<div id=\"div-login-msg\">\n");
      out.write("                                <div id=\"icon-login-msg\" class=\"glyphicon glyphicon-chevron-right\"></div>\n");
      out.write("                                <span id=\"text-login-msg\">Type your username and password.</span>\n");
      out.write("                            </div>\n");
      out.write("\t\t\t\t    \t\t<input id=\"login_username\" name=\"login_username\" class=\"form-control\" type=\"text\" placeholder=\"Username\" required>\n");
      out.write("\t\t\t\t    \t\t<input id=\"login_password\" name=\"login_password\" class=\"form-control\" type=\"password\" placeholder=\"Password\" required>\n");
      out.write("\t\t\t\t    \t\t\t<input class=\"sessionId\" name=\"sessionId\" type=\"hidden\" />\n");
      out.write("                            <div class=\"checkbox\">\n");
      out.write("                                <label>\n");
      out.write("                                    <input type=\"checkbox\"> Remember me\n");
      out.write("                                </label>\n");
      out.write("                            </div>\n");
      out.write("        \t\t    \t</div>\n");
      out.write("\t\t\t\t        <div class=\"modal-footer\">\n");
      out.write("                            <div>\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-primary btn-lg btn-block\" onClick=\"innerLogin()\">Login</button>\n");
      out.write("                            </div>\n");
      out.write("\t\t\t\t    \t    <div>\n");
      out.write("                                <button id=\"login_lost_btn\" type=\"button\" class=\"btn btn-link\">Lost Password?</button>\n");
      out.write("                                <button id=\"login_register_btn\" type=\"button\" class=\"btn btn-link\">Register</button>\n");
      out.write("                            </div>\n");
      out.write("\t\t\t\t        </div>\n");
      out.write("\t\t\t\t        <input type=\"hidden\" name=\"idType\" value=\"inner\">\n");
      out.write("                    </form>\n");
      out.write("                    <!-- End # Login Form -->\n");
      out.write("                    \n");
      out.write("                    <!-- Begin | Lost Password Form -->\n");
      out.write("                    <form id=\"lost-form\" style=\"display:none;\" method=\"GET\" ACTION=\"InputMailforAuth.do\" >\n");
      out.write("    \t    \t\t    <div class=\"modal-body\">\n");
      out.write("\t\t    \t\t\t\t<div id=\"div-lost-msg\">\n");
      out.write("                                <div id=\"icon-lost-msg\" class=\"glyphicon glyphicon-chevron-right\"></div>\n");
      out.write("                                <span id=\"text-lost-msg\">Type your e-mail.</span>\n");
      out.write("                            </div>\n");
      out.write("\t\t    \t\t\t\t<input id=\"lost_email\" name=\"lost_email\" class=\"form-control\" type=\"text\" placeholder=\"E-Mail\" required>\n");
      out.write("            \t\t\t</div>\n");
      out.write("\t\t    \t\t    <div class=\"modal-footer\">\n");
      out.write("                            <div>\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-primary btn-lg btn-block\" onclick=\"lostpassword()\">Send</button>\n");
      out.write("                            </div>\n");
      out.write("                            <div>\n");
      out.write("                                <button id=\"lost_login_btn\" type=\"button\" class=\"btn btn-link\">Log In</button>\n");
      out.write("                                <button id=\"lost_register_btn\" type=\"button\" class=\"btn btn-link\">Register</button>\n");
      out.write("                            </div>\n");
      out.write("\t\t    \t\t    </div>\n");
      out.write("                    </form>\n");
      out.write("                    <!-- End | Lost Password Form -->\n");
      out.write("                    \n");
      out.write("                    <!-- Begin | Register Form -->\n");
      out.write("                    <form id=\"register-form\" style=\"display:none;\" method=\"GET\" ACTION=\"join.do\">\n");
      out.write("            \t\t    <div class=\"modal-body\">\n");
      out.write("\t\t    \t\t\t\t<div id=\"div-register-msg\">\n");
      out.write("                                <div id=\"icon-register-msg\" class=\"glyphicon glyphicon-chevron-right\"></div>\n");
      out.write("                                <span id=\"text-register-msg\">Register an account.</span>\n");
      out.write("                            </div>\n");
      out.write("\t\t    \t\t\t\t<input id=\"register_username\" name=\"register_username\" class=\"form-control\" title=\"Username may only contain alphanumeric characters\" type=\"text\" placeholder=\"Username\" required>\n");
      out.write("                            <input id=\"register_email\" name=\"register_email\" class=\"form-control\" type=\"email\" placeholder=\"E-Mail\" required>\n");
      out.write("                            <input id=\"register_password\" name=\"register_password\" class=\"form-control\" title=\"minimum is 8 characters. and contain special character, numeric\" type=\"password\" placeholder=\"Password\" required>\n");
      out.write("\t\t\t\t\t\t\t<input id=\"register_password2\" onchange=\"\" class=\"form-control\" type=\"password\" placeholder=\"Rewrite password\" required>\n");
      out.write("            \t\t\t</div>\n");
      out.write("\t\t    \t\t    <div class=\"modal-footer\">\n");
      out.write("                            <div>\n");
      out.write("                                <button type=\"submit\" onclick=\"chkNickname()\" class=\"btn btn-primary btn-lg btn-block\">Register</button>\n");
      out.write("                            </div>\n");
      out.write("                            <div>\n");
      out.write("                                <button id=\"register_login_btn\" type=\"button\" class=\"btn btn-link\">Log In</button>\n");
      out.write("                                <button id=\"register_lost_btn\" type=\"button\" class=\"btn btn-link\">Lost Password?</button>\n");
      out.write("                            </div>\n");
      out.write("\t\t    \t\t    </div>\n");
      out.write("\t\t    \t\t   \t\t\t <input class=\"sessionId\" name=\"sessionId\" type=\"hidden\" />\n");
      out.write("\t\t    \t\t  \t\t\t  <input type=\"hidden\" name=\"idType\" value=\"inner\">\n");
      out.write("                    </form>\n");
      out.write("                    <!-- End | Register Form -->\n");
      out.write("                </div>\n");
      out.write("                <!-- End # DIV Form -->\n");
      out.write("                \n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("    <!-- END # MODAL LOGIN -->\n");
      out.write("\n");
      out.write("\t<div class=\"modal fade\" id=\"Register-edit-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\" style=\"display: none;\">\n");
      out.write("    \t<div class=\"modal-dialog\">\n");
      out.write("\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t<div class=\"modal-header\" align=\"center\">\n");
      out.write("\t\t\t\t\t<img class=\"img-circle\" id=\"img_logo2\" src=\"WidgetClientPage/img/test1.jpg\">\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("\t\t\t\t\t\t<span class=\"glyphicon glyphicon-remove\" aria-hidden=\"true\"></span>\n");
      out.write("\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("                \n");
      out.write("                <!-- Begin # DIV Form -->\n");
      out.write("                <div id=\"div-forms\">\n");
      out.write("\t\t\t\t\t<!-- Begin | Register Edit Form -->\n");
      out.write("\t\t\t\t\t<form id=\"register-edit-form\"  method=\"GET\" ACTION=\"changePasswd.do\">\n");
      out.write("            \t\t    <div class=\"modal-body\">\n");
      out.write("\t\t    \t\t\t\t<div id=\"div-edit-register-msg\">\n");
      out.write("                                <div id=\"icon-edit-register-msg\" class=\"glyphicon glyphicon-chevron-right\"></div>\n");
      out.write("                                <span id=\"text-register-msg\">Edit User info</span>\n");
      out.write("                            </div>\n");
      out.write("                            <input id=\"register_edit_password\" class=\"form-control\" title=\"minimum is 8 characters. and contain special character, numeric\" type=\"password\" placeholder=\"Password\" required>\n");
      out.write("            \t\t\t</div>\n");
      out.write("\t\t    \t\t    <div class=\"modal-footer\">\n");
      out.write("                            <div>\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-primary btn-lg btn-block\">submit</button>\n");
      out.write("                            </div>\n");
      out.write("\t\t    \t\t    </div>\n");
      out.write("                    </form>\n");
      out.write("\t\t\t\t\t<!-- End | Register Edit Form -->\n");
      out.write("                </div>\n");
      out.write("                <!-- End # DIV Form -->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<form method=\"GET\" ACTION=\"logout.do\" id=\"logout-form\">\n");
      out.write("\t\t<input id=\"sessionId_logout\" name=\"sessionId\" type=\"hidden\" />\n");
      out.write("\t</form>\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\t<form method=\"GET\" ACTION=\"verify.do\" id=\"chkRegister_chk_form\">\n");
      out.write("\t\t\t\t<input type = \"hidden\" name = \"nickname\" value = \"\" >\n");
      out.write("\t\t\t\t<input type = \"hidden\" name = \"email\" value = \"\" >\n");
      out.write("\t</form>\n");
      out.write("    <!-- jQuery -->\n");
      out.write("    <script src=\"WidgetClientPage/js/jquery.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap Core JavaScript -->\n");
      out.write("    <script src=\"WidgetClientPage/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Custom Theme JavaScript -->\n");
      out.write("    <script>\n");
      out.write("\twindow.onload=function(){\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t");

			try{ 
				//ìëë¡ê·¸ì¸ ì²ë¦¬íê¸°    
				if(request.getAttribute("doLogout")!= null && 	((String)request.getAttribute("doLogout")).equals("true")){
					session.removeAttribute("alreayLogin");
					
      out.write("\n");
      out.write("\t\t\t\t\t\talert(\"Bye...\");\n");
      out.write("\t\t\t\t\t");

				}
				else if(request.getAttribute("isSuccessJoin")!= null && 	((String)request.getAttribute("isSuccessJoin")).equals("true")){
					
      out.write("\n");
      out.write("\t\t\t\t\talert(\" ");
      out.print( request.getAttribute("message") );
      out.write("\");\n");
      out.write("\t\t\t\t\t");

				}
				else if(request.getAttribute("alreadyLogin") != null &&	((String) request.getAttribute("alreadyLogin")).equals("true")){
								//response.sendRedirect("main.jsp");
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\tsignChange('signOut');\n");
      out.write("\t\t\t\t\t\t\t");

					}
				//ë¡ê·¸ì¸ ê²°ê³¼ ì»ê¸° 
				else if( request.getAttribute("isSuccessLogin") != null && ((String)request.getAttribute("isSuccessLogin")).equals("true")){	
					
      out.write("\n");
      out.write("\t\t\t\t\tsignChange('signOut');\n");
      out.write("\t\t\t\t\t");

					session.setAttribute("alreadyLogin", "true");
					session.setMaxInactiveInterval(60*60);	
					
				}
				else if( ((String)session.getAttribute("isSuccessLogin")).equals("false") == true ){
					if( session.getAttribute("message")!=null)
						
      out.write("\n");
      out.write("\t\t\t\t\t\t\talert(");
      out.print((String)session.getAttribute("message"));
      out.write(");\n");
      out.write("\t\t\t\t\t\t");
	
				}
			}
			catch(Exception e){
				e.printStackTrace();
			} 
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t};\n");
      out.write("\n");
      out.write("\tfunction fun_Store(){\n");
      out.write("\t\t $(\"#menu-close\").click();\n");
      out.write("\t\tresponse.forward(\"./store.jsp\");\n");
      out.write("\t\t\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction fun_signOut(){\n");
      out.write("\t\tvar id = \"");
      out.print( (String)session.getId() );
      out.write("\";\n");
      out.write("//\t\tdocument.getElementsByName(\"sessionId_logout\")[0].value = id;\n");
      out.write("\t\t$(\"#sessionId_logout\").val(id);\n");
      out.write("\t\tdocument.forms[\"logout-form\"].submit();\n");
      out.write("\t\treturn;\t\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction innerLogin(){\n");
      out.write("\t\tvar id = \"");
      out.print( (String)session.getId() );
      out.write("\";\n");
      out.write("\t\t$(\".sessionId\").val(id);\n");
      out.write("\t\tdocument.forms[\"login-form\"].submit();\n");
      out.write("\t}\n");
      out.write("\tfunction innerJoin(){\n");
      out.write("\t\tvar id = \"");
      out.print( (String)session.getId() );
      out.write("\";\n");
      out.write("\t\t$(\".sessionId\").val(id);\n");
      out.write("\t\tdocument.forms[\"register-form\"].submit();\n");
      out.write("\t}\n");
      out.write("\tfunction lostpassword(){\n");
      out.write("\t\tdocument.forms[\"lost-form\"].submit();\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction signChange(id){\n");
      out.write("\tvar div = document.getElementById(id);\n");
      out.write("\t\tif(div.style.display=='none'){\n");
      out.write("          div.style.display='';\n");
      out.write("\t\t\n");
      out.write("\t\t  if(id==\"signOut\"){\n");
      out.write("\t\t    var div_sp = document.getElementById('signIn');\n");
      out.write("\t\t\tdiv_sp.style.display='none';\n");
      out.write("\t\t  }else{\n");
      out.write("\t\t   var div_sp = document.getElementById('signOut');\n");
      out.write("\t\t\tdiv_sp.style.display='none';\n");
      out.write("\t\t  }\n");
      out.write("\t\t}\n");
      out.write("   }\n");
      out.write("\t\n");
      out.write("    // Closes the sidebar menu\n");
      out.write("    $(\"#menu-close\").click(function(e) {\n");
      out.write("        e.preventDefault();\n");
      out.write("        $(\"#sidebar-wrapper\").toggleClass(\"active\");\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    // Opens the sidebar menu\n");
      out.write("    $(\"#menu-toggle\").click(function(e) {\n");
      out.write("        e.preventDefault();\n");
      out.write("        $(\"#sidebar-wrapper\").toggleClass(\"active\");\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    /* #####################################################################\n");
      out.write("   #\n");
      out.write("   #   Project       : Modal Login with jQuery Effects\n");
      out.write("   #   Author        : Rodrigo Amarante (rodrigockamarante)\n");
      out.write("   #   Version       : 1.0\n");
      out.write("   #   Created       : 07/29/2015\n");
      out.write("   #   Last Change   : 08/04/2015\n");
      out.write("   #\n");
      out.write("   ##################################################################### */\n");
      out.write("   \n");
      out.write("\t$(function() {\n");
      out.write("    \n");
      out.write("    var $formLogin = $('#login-form');\n");
      out.write("    var $formLost = $('#lost-form');\n");
      out.write("    var $formRegister = $('#register-form');\n");
      out.write("\tvar $formEditRegister = $('#register-edit-form');\n");
      out.write("    var $divForms = $('#div-forms');\n");
      out.write("    var $modalAnimateTime = 300;\n");
      out.write("    var $msgAnimateTime = 150;\n");
      out.write("    var $msgShowTime = 2000;\n");
      out.write("\n");
      out.write("    $(\"form\").submit(function () {\n");
      out.write("        switch(this.id) {\n");
      out.write("            case \"login-form\":\n");
      out.write("                var $lg_username=$('#login_username').val();\n");
      out.write("                var $lg_password=$('#login_password').val();\n");
      out.write("\n");
      out.write("                if (");
      out.print(request.getAttribute("innerLogin"));
      out.write(" == \"false\") {\n");
      out.write("                    msgChange($('#div-login-msg'), $('#icon-login-msg'), $('#text-login-msg'), \"error\", \"glyphicon-remove\", \"Login error\");\n");
      out.write("                } else {\n");
      out.write("                    msgChange($('#div-login-msg'), $('#icon-login-msg'), $('#text-login-msg'), \"success\", \"glyphicon-ok\", \"Login OK\");\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t//window.location.reload();\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\treturn true;\n");
      out.write("\t\t\t\t\t\t                }\n");
      out.write("\t\t\t\t\n");
      out.write("                return false;\n");
      out.write("                break;\n");
      out.write("            case \"lost-form\":\n");
      out.write("                var $ls_email=$('#lost_email').val();\n");
      out.write("                if (");
      out.print(request.getAttribute("inputMail"));
      out.write(" == \"false\") {\n");
      out.write("                    msgChange($('#div-lost-msg'), $('#icon-lost-msg'), $('#text-lost-msg'), \"error\", \"glyphicon-remove\", \"Send error\");\n");
      out.write("                } else {\n");
      out.write("                    msgChange($('#div-lost-msg'), $('#icon-lost-msg'), $('#text-lost-msg'), \"success\", \"glyphicon-ok\", \"Send OK\");\n");
      out.write("\t\t\t\t\treturn true;\n");
      out.write("\t\t\t\t}\n");
      out.write("                return false;\n");
      out.write("                break;\n");
      out.write("            case \"register-form\":\n");
      out.write("                var $rg_username=$('#register_username').val();\n");
      out.write("                var $rg_email=$('#register_email').val();\n");
      out.write("                var $rg_password=$('#register_password').val();\n");
      out.write("\t\t\t\tvar $rg_password2=$('#register_password2').val();\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tif (!CheckName()) {\n");
      out.write("                    msgChange($('#div-register-msg'), $('#icon-register-msg'), $('#text-register-msg'), \"error\", \"glyphicon-remove\", \"CHECK USERNAME\");\n");
      out.write("                } else if(!chkPwd($rg_password, $rg_password2)) {\n");
      out.write("                    msgChange($('#div-register-msg'), $('#icon-register-msg'), $('#text-register-msg'), \"error\", \"glyphicon-remove\", \"CHECK PASSWORD\");\n");
      out.write("                } else if(chkRegister()&&");
      out.print(request.getAttribute("isDuplicatedNickname"));
      out.write(" == \"true\"){\n");
      out.write("\t\t\t\t\tmsgChange($('#div-register-msg'), $('#icon-register-msg'), $('#text-register-msg'), \"error\", \"glyphicon-remove\", \"CHECK NICKNAME\");\n");
      out.write("\t\t\t\t} else{\n");
      out.write("                    msgChange($('#div-register-msg'), $('#icon-register-msg'), $('#text-register-msg'), \"success\", \"glyphicon-ok\", \"Register OK\");\n");
      out.write("\t\t\t\t\treturn true;\n");
      out.write("                }\n");
      out.write("                return false;\n");
      out.write("                break;\n");
      out.write("\t\t\tcase \"register-edit-form\":\n");
      out.write("\t\t\t\tif(true){\n");
      out.write("\t\t\t\t\t//ÃÂ¬ÃÂÃÂ¬ÃÂªÃÂ¸ÃÂ°ÃÂ¬ÃÂÃÂ ÃÂ¬ÃÂÃÂÃÂ«ÃÂ¡ÃÂÃÂ¬ÃÂÃÂÃÂªÃÂ¸ÃÂ´ ÃÂ«ÃÂ¹ÃÂÃÂ«ÃÂ°ÃÂÃÂ«ÃÂ²ÃÂÃÂ­ÃÂÃÂ¸,,\n");
      out.write("\t\t\t\t}\n");
      out.write("            default:\n");
      out.write("                return false;\n");
      out.write("        }\n");
      out.write("        return false;\n");
      out.write("    });\n");
      out.write("    \n");
      out.write("    $('#login_register_btn').click( function () { modalAnimate($formLogin, $formRegister) });\n");
      out.write("    $('#register_login_btn').click( function () { modalAnimate($formRegister, $formLogin); });\n");
      out.write("    $('#login_lost_btn').click( function () { modalAnimate($formLogin, $formLost); });\n");
      out.write("    $('#lost_login_btn').click( function () { modalAnimate($formLost, $formLogin); });\n");
      out.write("    $('#lost_register_btn').click( function () { modalAnimate($formLost, $formRegister); });\n");
      out.write("    $('#register_lost_btn').click( function () { modalAnimate($formRegister, $formLost); });\n");
      out.write("    \n");
      out.write("    function modalAnimate ($oldForm, $newForm) {\n");
      out.write("        var $oldH = $oldForm.height();\n");
      out.write("        var $newH = $newForm.height();\n");
      out.write("        $divForms.css(\"height\",$oldH);\n");
      out.write("        $oldForm.fadeToggle($modalAnimateTime, function(){\n");
      out.write("            $divForms.animate({height: $newH}, $modalAnimateTime, function(){\n");
      out.write("                $newForm.fadeToggle($modalAnimateTime);\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    function msgFade ($msgId, $msgText) {\n");
      out.write("        $msgId.fadeOut($msgAnimateTime, function() {\n");
      out.write("            $(this).text($msgText).fadeIn($msgAnimateTime);\n");
      out.write("        });\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    function msgChange($divTag, $iconTag, $textTag, $divClass, $iconClass, $msgText) {\n");
      out.write("        var $msgOld = $divTag.text();\n");
      out.write("        msgFade($textTag, $msgText);\n");
      out.write("        $divTag.addClass($divClass);\n");
      out.write("        $iconTag.removeClass(\"glyphicon-chevron-right\");\n");
      out.write("        $iconTag.addClass($iconClass + \" \" + $divClass);\n");
      out.write("        setTimeout(function() {\n");
      out.write("            msgFade($textTag, $msgOld);\n");
      out.write("            $divTag.removeClass($divClass);\n");
      out.write("            $iconTag.addClass(\"glyphicon-chevron-right\");\n");
      out.write("            $iconTag.removeClass($iconClass + \" \" + $divClass);\n");
      out.write("  \t\t}, $msgShowTime);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("\tfunction chkRegister(){\n");
      out.write("\t\tdocument.getElementsByName(\"rg_nickname\")[1].value = document.getElementById(\"register_username\").value;\n");
      out.write("\t\tdocument.getElementsByName(\"rg_emali\")[1].value = document.getElementById(\"register_email\").value;\n");
      out.write("\t\tdocument.forms[\"chkRegister_chk_form\"].submit();\n");
      out.write("\t\t\n");
      out.write("\t\treturn true;\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction CheckName(){\n");
      out.write("\t\tvar flag = true;\n");
      out.write("\t\tvar specialChars=\" ~`!@#$%^&*-=+\\|[](){};:'<.,>/?_\";\n");
      out.write("\t\tvar wordadded = $('#register_username').val();\n");
      out.write("\t\tif(wordadded = \"\") flag = false;\n");
      out.write("\t\tfor (i = 0; i < wordadded.length; i++) {\n");
      out.write("\t\t\tfor (j = 0; j < specialChars.length; j++) {         \n");
      out.write("\t\t\t\tif (wordadded.charAt(i) == specialChars.charAt(j)){         \n");
      out.write("\t\t\t\t\tflag=false;\n");
      out.write("\t\t\t\t\tbreak;\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t\treturn flag;\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction chkPwd(str, str2){\n");
      out.write("\t\tvar pw = str;\n");
      out.write("\t\tvar pw2 = str2;\n");
      out.write("\t\tvar num = pw.search(/[0-9]/g);\n");
      out.write("\t\tvar eng = pw.search(/[a-z]/ig);\n");
      out.write("\t\tvar spe = pw.search(/[`~!@@#$%^&*|ÃÂ¢ÃÂÃÂ©ÃÂ¢ÃÂÃÂ©ÃÂ¢ÃÂÃÂ©'ÃÂ¢ÃÂÃÂ©\";:ÃÂ¢ÃÂÃÂ©/?]/gi);\n");
      out.write("\n");
      out.write("\t\t if(pw.length < 8 || pw.length > 20){\n");
      out.write("\t\t\talert(\"8ÃÂ¬ÃÂÃÂÃÂ«ÃÂ¦ÃÂ¬ ~ 20ÃÂ¬ÃÂÃÂÃÂ«ÃÂ¦ÃÂ¬ ÃÂ¬ÃÂÃÂ´ÃÂ«ÃÂÃÂ´ÃÂ«ÃÂ¡ÃÂ ÃÂ¬ÃÂÃÂÃÂ«ÃÂ ÃÂ¥ÃÂ­ÃÂÃÂ´ÃÂ¬ÃÂ£ÃÂ¼ÃÂ¬ÃÂÃÂ¸ÃÂ¬ÃÂÃÂ.\");\n");
      out.write("\t\t\treturn false;\n");
      out.write("\t\t }\n");
      out.write("\t\t else if(pw.search(/ÃÂ¢ÃÂÃÂ©s/) != -1){\n");
      out.write("\t\t\talert(\"ÃÂ«ÃÂ¹ÃÂÃÂ«ÃÂ°ÃÂÃÂ«ÃÂ²ÃÂÃÂ­ÃÂÃÂ¸ÃÂ«ÃÂÃÂ ÃÂªÃÂ³ÃÂµÃÂ«ÃÂ°ÃÂ±ÃÂ¬ÃÂÃÂÃÂ¬ÃÂÃÂ´ ÃÂ¬ÃÂÃÂÃÂ«ÃÂ ÃÂ¥ÃÂ­ÃÂÃÂ´ÃÂ¬ÃÂ£ÃÂ¼ÃÂ¬ÃÂÃÂ¸ÃÂ¬ÃÂÃÂ.\");\n");
      out.write("\t\t\treturn false;\n");
      out.write("\t\t } \n");
      out.write("\t\t else if(num < 0 || eng < 0 || spe < 0 ){\n");
      out.write("\t\t\talert(\"ÃÂ¬ÃÂÃÂÃÂ«ÃÂ¬ÃÂ¸,ÃÂ¬ÃÂÃÂ«ÃÂ¬ÃÂÃÂ, ÃÂ­ÃÂÃÂ¹ÃÂ¬ÃÂÃÂÃÂ«ÃÂ¬ÃÂ¸ÃÂ¬ÃÂÃÂÃÂ«ÃÂ¥ÃÂ¼ ÃÂ­ÃÂÃÂ¼ÃÂ­ÃÂÃÂ©ÃÂ­ÃÂÃÂÃÂ¬ÃÂÃÂ¬ ÃÂ¬ÃÂÃÂÃÂ«ÃÂ ÃÂ¥ÃÂ­ÃÂÃÂ´ÃÂ¬ÃÂ£ÃÂ¼ÃÂ¬ÃÂÃÂ¸ÃÂ¬ÃÂÃÂ.\");\n");
      out.write("\t\t\treturn false;\n");
      out.write("\t\t }\n");
      out.write("\t\t else if(str != str2){\n");
      out.write("\t\t\talert(\"ÃÂ«ÃÂ¹ÃÂÃÂ«ÃÂ°ÃÂÃÂ«ÃÂ²ÃÂÃÂ­ÃÂÃÂ¸ÃÂªÃÂ°ÃÂ ÃÂ¬ÃÂÃÂÃÂ«ÃÂ¡ÃÂ ÃÂ«ÃÂ§ÃÂÃÂ¬ÃÂ§ÃÂ ÃÂ¬ÃÂÃÂÃÂ¬ÃÂÃÂµÃÂ«ÃÂÃÂÃÂ«ÃÂÃÂ¤.\");\n");
      out.write("\t\t\treturn false;\n");
      out.write("\t\t }\n");
      out.write("\t\t else {\n");
      out.write("\t\t\treturn true;\n");
      out.write("\t\t }\n");
      out.write("\t}\n");
      out.write("});\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t//------------start tooltip line\n");
      out.write("\tvar qTipTag = \"i,input\"; //Which tags do you want to qTip-ize? Keep it lowercase!//\n");
      out.write("\tvar qTipX = 0; //This is qTip's X offset//\n");
      out.write("\tvar qTipY = 15; //This is qTip's Y offset//\n");
      out.write("\n");
      out.write("\t//There's no need to edit anything below this line//\n");
      out.write("\ttooltip = {\n");
      out.write("\t\tname : \"qTip\",\n");
      out.write("\t\toffsetX : qTipX,\n");
      out.write("\t\toffsetY : qTipY,\n");
      out.write("\t\ttip : null\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\ttooltip.init = function () {\n");
      out.write("\t\tvar tipNameSpaceURI = \"http://www.w3.org/1999/xhtml\";\n");
      out.write("\t\tif(!tipContainerID){ var tipContainerID = \"qTip\";}\n");
      out.write("\t\tvar tipContainer = document.getElementById(tipContainerID);\n");
      out.write("\n");
      out.write("\t\tif(!tipContainer) {\n");
      out.write("\t\t\ttipContainer = document.createElementNS ? document.createElementNS(tipNameSpaceURI, \"div\") : document.createElement(\"div\");\n");
      out.write("\t\t\ttipContainer.setAttribute(\"id\", tipContainerID);\n");
      out.write("\t\t\tdocument.getElementsByTagName(\"body\").item(0).appendChild(tipContainer);\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tif (!document.getElementById) return;\n");
      out.write("\t\tthis.tip = document.getElementById (this.name);\n");
      out.write("\t\tif (this.tip) document.onmousemove = function (evt) {tooltip.move (evt)};\n");
      out.write("\n");
      out.write("\t\tvar a, sTitle, elements;\n");
      out.write("    \n");
      out.write("\t\tvar elementList = qTipTag.split(\",\");\n");
      out.write("\t\tfor(var j = 0; j < elementList.length; j++)\n");
      out.write("\t\t{    \n");
      out.write("\t\t\telements = document.getElementsByTagName(elementList[j]);\n");
      out.write("\t\t\tif(elements)\n");
      out.write("\t\t\t{\n");
      out.write("\t\t\t\tfor (var i = 0; i < elements.length; i ++)\n");
      out.write("\t\t\t\t{\n");
      out.write("\t\t\t\t\ta = elements[i];\n");
      out.write("\t\t\t\t\tsTitle = a.getAttribute(\"title\");                \n");
      out.write("\t\t\t\t\tif(sTitle)\n");
      out.write("\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\ta.setAttribute(\"tiptitle\", sTitle);\n");
      out.write("\t\t\t\t\t\ta.removeAttribute(\"title\");\n");
      out.write("\t\t\t\t\t\ta.removeAttribute(\"alt\");\n");
      out.write("\t\t\t\t\t\ta.onmouseover = function() {tooltip.show(this.getAttribute('tiptitle'))};\n");
      out.write("\t\t\t\t\t\ta.onmouseout = function() {tooltip.hide()};\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\ttooltip.move = function (evt) {\n");
      out.write("\t\tvar x=0, y=0;\n");
      out.write("\t\tif (document.all) {//IE\n");
      out.write("\t\t\tx = (document.documentElement && document.documentElement.scrollLeft) ? document.documentElement.scrollLeft : document.body.scrollLeft;\n");
      out.write("\t\t\ty = (document.documentElement && document.documentElement.scrollTop) ? document.documentElement.scrollTop : document.body.scrollTop;\n");
      out.write("\t\t\tx += window.event.clientX;\n");
      out.write("\t\t\ty += window.event.clientY;\n");
      out.write("\t\t\t\n");
      out.write("\t\t} else {//Good Browsers\n");
      out.write("\t\t\tx = evt.pageX;\n");
      out.write("\t\t\ty = evt.pageY;\n");
      out.write("\t\t}\n");
      out.write("\t\tthis.tip.style.left = (x + this.offsetX) + \"px\";\n");
      out.write("\t\tthis.tip.style.top = (y + this.offsetY) + \"px\";\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\ttooltip.show = function (text) {\n");
      out.write("\t\tif (!this.tip) return;\n");
      out.write("\t\tthis.tip.innerHTML = text;\n");
      out.write("\t\tthis.tip.style.display = \"block\";\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\ttooltip.hide = function () {\n");
      out.write("\t\tif (!this.tip) return;\n");
      out.write("\t\tthis.tip.innerHTML = \"\";\n");
      out.write("\t\tthis.tip.style.display = \"none\";\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\t// Multiple onload function created by: Simon Willison\n");
      out.write("\t// http://simonwillison.net/2004/May/26/addLoadEvent/\n");
      out.write("\tfunction addLoadEvent(func) {\n");
      out.write("\t  var oldonload = window.onload;\n");
      out.write("\t  if (typeof window.onload != 'function') {\n");
      out.write("\t\twindow.onload = func\n");
      out.write("\t  } else {\n");
      out.write("\t\twindow.onload = function() {\n");
      out.write("\t\t  if (oldonload) {\n");
      out.write("\t\t\toldonload();\n");
      out.write("\t\t  }\n");
      out.write("\t\t  func();\n");
      out.write("\t\t}\n");
      out.write("\t  }\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\taddLoadEvent(function() {\n");
      out.write("\t  tooltip.init ();\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
