/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-09-03 09:31:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class Store_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");


	request.setCharacterEncoding("UTF-8");


      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("    <title>WidgetStore - STORE</title>\r\n");
      out.write("    <!-- Bootstrap Core CSS -->\r\n");
      out.write("    <link href=\"WidgetClientPage/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link href=\"WidgetClientPage/css/shop-homepage.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body onload=\"init()\">\r\n");
      out.write("    <!-- Navigation -->\r\n");
      out.write("    <nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("            <div class=\"navbar-header\">\r\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\r\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"#\">WIDGET STORE</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("            <!-- 상위 메뉴 -->\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("                <ul class=\"nav navbar-nav\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\" onClick=\"fun_develop()\">Develop</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">Services</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">Contact</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.navbar-collapse -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.container -->\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!-- Page Content -->\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-3\">\r\n");
      out.write("                    <p class=\"lead\">WidgetStore</p>\r\n");
      out.write("                    <div class=\"list-group\">\r\n");
      out.write("                        <a href=\"#\" class=\"list-group-item\">생활</a>\r\n");
      out.write("                        <a href=\"#\" class=\"list-group-item\">스포츠</a>\r\n");
      out.write("                        <a href=\"#\" class=\"list-group-item\">검색</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-9\">\r\n");
      out.write("                    <!--\r\n");
      out.write("                    <div class=\"row carousel-holder\">\r\n");
      out.write("            \r\n");
      out.write("                        <div class=\"col-md-12\">\r\n");
      out.write("                            <div id=\"carousel-example-generic\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("                                <ol class=\"carousel-indicators\">\r\n");
      out.write("                                    <li data-target=\"#carousel-example-generic\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("                                    <li data-target=\"#carousel-example-generic\" data-slide-to=\"1\"></li>\r\n");
      out.write("                                    <li data-target=\"#carousel-example-generic\" data-slide-to=\"2\"></li>\r\n");
      out.write("                                </ol>\r\n");
      out.write("                                <div class=\"carousel-inner\">\r\n");
      out.write("                                    <div class=\"item active\">\r\n");
      out.write("                                        <img class=\"slide-image\" src=\"over.jpg\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"item\">\r\n");
      out.write("                                        <img class=\"slide-image\" src=\"closer.jpg\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"item\">\r\n");
      out.write("                                        <img class=\"slide-image\" src=\"deon.jpg\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <a class=\"left carousel-control\" href=\"#carousel-example-generic\" data-slide=\"prev\">\r\n");
      out.write("                                    <span class=\"glyphicon glyphicon-chevron-left\"></span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a class=\"right carousel-control\" href=\"#carousel-example-generic\" data-slide=\"next\">\r\n");
      out.write("                                    <span class=\"glyphicon glyphicon-chevron-right\"></span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("            \r\n");
      out.write("                    </div>\r\n");
      out.write("                    -->\r\n");
      out.write("                    <!-- 상세보기 부분 -->\r\n");
      out.write("                    <div class='widgetInfo' id='widgetInfo' style=\"display: none;\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <!-- 위젯의 메인 사진과 작성자 -->\r\n");
      out.write("                            <div class='goodsMain'>\r\n");
      out.write("                                <img src='http://placehold.it/150x150' alt=''>\r\n");
      out.write("                                <h1 id='widgetName'></h1>\r\n");
      out.write("                                <h4 id='widgetDeveloperName'></h4>\r\n");
      out.write("                                <h4 id='star'></h4>\r\n");
      out.write("                                <h5 id = 'grade'></h5>\r\n");
      out.write("                                <div class='btnBuy'>Download</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- 위젯의 설명용 사진과 설명 -->\r\n");
      out.write("                            <div class='goodsSub'>\r\n");
      out.write("                                <img src='http://placehold.it/550x150' alt=''>\r\n");
      out.write("                                <h5 id='widgetExplain'></h5>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- 리뷰 -->\r\n");
      out.write("                            <div class='goodsReview'>\r\n");
      out.write("                                <div id = 'widgetReview'></div>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <label>로그인한 작성자의 이름을 표시함</label>\r\n");
      out.write("                                    <!-- 덧글 다는 부분 -->\r\n");
      out.write("                                    <textarea id='msg'></textarea>\r\n");
      out.write("                                    <button onclick=\"submit()\">댓글달기</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class='goodsRank'>\r\n");
      out.write("                                <select name=\"rank\" onchange=\"javascript:getWidget()\" style=\"width:140px;margin:10px;\">\r\n");
      out.write("                                    <option value='5' selected>★★★★★</option>\r\n");
      out.write("                                    <option value='4' selected>★★★★☆</option>\r\n");
      out.write("                                    <option value='3' selected>★★★☆☆</option>\r\n");
      out.write("                                    <option value='2' selected>★★☆☆☆</option>\r\n");
      out.write("                                    <option value='1' selected>★☆☆☆☆</option>\r\n");
      out.write("                                    <option value='' selected></option>\r\n");
      out.write("                                    \r\n");
      out.write("                                    </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"field\" class=\"row\">\r\n");
      out.write("                        <script type=\"text/javascript\">\r\n");
      out.write("                        function init() {\r\n");
      out.write("                            // db에서 불러온 위젯의 id에 따라 적절한 위젯을 붙임.\r\n");
      out.write("                            addItem(1);\r\n");
      out.write("                            addItem(2);\r\n");
      out.write("                            addItem(3);\r\n");
      out.write("                            addItem(4);\r\n");
      out.write("                            addItem(5);\r\n");
      out.write("                            addItem(6);\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        // 덧글을 다는 함수\r\n");
      out.write("                        function submit() {\r\n");
      out.write("                            //\r\n");
      out.write("                            // 서버에 저장하는 부분이 필요함.\r\n");
      out.write("                            // \r\n");
      out.write("                            // \r\n");
      out.write("                            // \r\n");
      out.write("                            // \r\n");
      out.write("                            // \r\n");
      out.write("                            var text = document.getElementById('msg');\r\n");
      out.write("                            if (text.value == \"\") {\r\n");
      out.write("                                alert(\"내용이 없음\");\r\n");
      out.write("                                return;\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            showReview(\"아이디\", text.value);\r\n");
      out.write("                            text.value = \"\";\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        // 전체 내용을 표시하는 함수\r\n");
      out.write("                        function open_detail(widgetId) {\r\n");
      out.write("                            // 숨겨졌던 폼을 로드함.\r\n");
      out.write("                            if (!document.getElementById('widgetInfo').style.display == \"\") {\r\n");
      out.write("                                document.getElementById('widgetInfo').style.display = '';\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            if(typeof(reviews)!='undefined')\r\n");
      out.write("                            {\r\n");
      out.write("                                document.getElementById('reviews').remove();\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                            document.getElementById(\"widgetName\").innerText = \"\" + widgetId + \"의 위젯 이름임\";\r\n");
      out.write("                            document.getElementById('widgetDeveloperName').innerText = \"\" + widgetId + \"의 개발자 이름임\";\r\n");
      out.write("                            document.getElementById('grade').innerText = \"평점 :  4.5\";\r\n");
      out.write("                            document.getElementById('star').innerText = \"★★★★☆\";\r\n");
      out.write("                            document.getElementById('widgetExplain').innerText =\r\n");
      out.write("\r\n");
      out.write("                                \"오늘도 또 우리 수탉이 막 쫓기었다.\\n\"\r\n");
      out.write("\r\n");
      out.write("                            + \"내가 점심을 먹고 나무를 하러 갈 양으로 나올 때이었다.\\n\"\r\n");
      out.write("\r\n");
      out.write("                            + \"산으로 올라서려니까 등뒤에서 푸르득푸드득, 하고 닭의 횃소리가 야단이다.\\n\"\r\n");
      out.write("\r\n");
      out.write("                            + \"깜짝 놀라서 고개를 돌려보니 아니나다르랴, 두 놈이 또 얼리었다.\\n\"\r\n");
      out.write("\r\n");
      out.write("                            + \"점순네 수탉(은 대강이가 크고 똑 오소리같이 실팍하게 생긴 놈)\"\r\n");
      out.write("\r\n");
      out.write("                            + \"이 덩저리 작은 우리 수탉을 함부로 해내는 것이다.\\n\"\r\n");
      out.write("\r\n");
      out.write("                            + \" 그것도 그냥 해내는 것이 아니라 푸드득 하고 면두를 쪼고 물러섰다가 좀 사이를 두고 또 푸드득 하고 모가지를 쪼았다. \\n\\n\"\r\n");
      out.write("\r\n");
      out.write("                            + \"김유정\\n\"\r\n");
      out.write("\r\n");
      out.write("                            + \"<동백꽃>\\n\";\r\n");
      out.write("\r\n");
      out.write("                            // 댓글을 한번에 지우기 위해\r\n");
      out.write("                            // 댓글 부븐을 동적으로 추가함\r\n");
      out.write("                            \r\n");
      out.write("\r\n");
      out.write("                            var div = document.createElement('div');\r\n");
      out.write("                            div.id = 'reviews';\r\n");
      out.write("                            document.getElementById('widgetReview').appendChild(div);\r\n");
      out.write("\r\n");
      out.write("                            // 덧글을 로드함\r\n");
      out.write("                            showReview(\"디바\", \"이것도 너프해보시지\");\r\n");
      out.write("                            showReview(\"라인하르트\", \"바스티온이 나가신다\");\r\n");
      out.write("                            showReview(\"정크랫\", \"폭탄 받아라\");\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        function showReview(name, text) {\r\n");
      out.write("                            // 위젯 번호에 따른 덧글을 표시함\r\n");
      out.write("\r\n");
      out.write("                            var div = document.createElement('div');\r\n");
      out.write("\r\n");
      out.write("                            var strHTML =\r\n");
      out.write("                                \"<h4 id='userName'> \" + name + \" </h4>\" + \"<h5 id='userReview'>\" + text + \"</h5>\";\r\n");
      out.write("\r\n");
      out.write("                            div.innerHTML = strHTML;\r\n");
      out.write("                            document.getElementById('reviews').appendChild(div);\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        function addItem(widgetID) {\r\n");
      out.write("                            var div = document.createElement('div');\r\n");
      out.write("                            // 방법 1.\r\n");
      out.write("                            // div.innerHTML = document.getElementById('aaa').outerHTML;\r\n");
      out.write("                            // document.getElementById('field').appendChild(div);\r\n");
      out.write("\r\n");
      out.write("                            // 방법 2.\r\n");
      out.write("                            // divId : field 내부의 div ID\r\n");
      out.write("                            // document.getElementById('divId').innerHTML = document.getElementById('aaa').outerHTML;\r\n");
      out.write("\r\n");
      out.write("                            // 방법 3.\r\n");
      out.write("                            var strHTML =\r\n");
      out.write("                                \"<div class='col-sm-4 col-lg-4 col-md-4' id ='testID\" + widgetID + \"'>\" + \"<div class='thumbnail'>\" + \"<img src='http://placehold.it/320x150' alt=''>\" + \"<div class='caption'>\" + \"<h4 class='pull-right'></h4>\" +\r\n");
      out.write("\r\n");
      out.write("                                '<h4 ><a href=\"JavaScript:;\" onclick=\"JavaScript: open_detail(' + widgetID + ');\">' + widgetID + \"</a></h4>\" +\r\n");
      out.write("\r\n");
      out.write("                                \"<p>이것은 실험용이다.</p></div>\" + \"<div class='ratings'>\" + \"<p class='pull-right'>18 reviews</p>\" + \"</div></div></div>\";\r\n");
      out.write("\r\n");
      out.write("                            div.innerHTML = strHTML;\r\n");
      out.write("                            document.getElementById('field').appendChild(div);\r\n");
      out.write("                        }\r\n");
      out.write("                        </script>\r\n");
      out.write("                        <!--\r\n");
      out.write("                        <div class=\"col-sm-4 col-lg-4 col-md-4\" id=\"aaa\">\r\n");
      out.write("                            <div class=\"thumbnail\">\r\n");
      out.write("                                <img src=\"http://placehold.it/320x150\" alt=\"\">\r\n");
      out.write("                                <div class=\"caption\">\r\n");
      out.write("                                    <h4 class=\"pull-right\"></h4>\r\n");
      out.write("                                    <h4><a href=\"JavaScript:;\" onclick=\"JavaScript: open_detail('1');\">Fifth Product</a></h4>\r\n");
      out.write("                                    <p>시험</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"ratings\">\r\n");
      out.write("                                    <p class=\"pull-right\">18 reviews</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        -->\r\n");
      out.write("                        <!--\r\n");
      out.write("                        <div class=\"col-sm-4 col-lg-4 col-md-4\">\r\n");
      out.write("                            <h4><a href=\"#\">View more Widget?</a>\r\n");
      out.write("                            </h4>\r\n");
      out.write("                            <p>If you like this template, then check out <a target=\"_blank\" href=\"http://maxoffsky.com/code-blog/laravel-shop-tutorial-1-building-a-review-system/\">this tutorial</a> on how to build a working review system for your online store!</p>\r\n");
      out.write("                            <a class=\"btn btn-primary\" target=\"_blank\" href=\"http://maxoffsky.com/code-blog/laravel-shop-tutorial-1-building-a-review-system/\">View Tutorial</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        -->\r\n");
      out.write("                        <!-- 페이지 컨트롤 -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"pageWrap\">\r\n");
      out.write("                        <ul class=\"pageControl\">\r\n");
      out.write("                            <li><a href=\"\"> 이전</a></li>\r\n");
      out.write("                            <li><a href=\"\"> 1</a></li>\r\n");
      out.write("                            <li><a href=\"\"> 2</a></li>\r\n");
      out.write("                            <li><a href=\"\"> 3</a></li>\r\n");
      out.write("                            <li><a href=\"\"> 4</a></li>\r\n");
      out.write("                            <li><a href=\"\"> 5</a></li>\r\n");
      out.write("                            <li><a href=\"\"> 6</a></li>\r\n");
      out.write("                            <li><a href=\"\"> 7</a></li>\r\n");
      out.write("                            <li><a href=\"\"> 8</a></li>\r\n");
      out.write("                            <li><a href=\"\"> 9</a></li>\r\n");
      out.write("                            <li><a href=\"\"> 10</a></li>\r\n");
      out.write("                            <li><a href=\"\"> 이후</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.container -->\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <hr>\r\n");
      out.write("        <!-- Footer -->\r\n");
      out.write("        <footer>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    제작자 : ㅇㅅㅇ\r\n");
      out.write("                    <!-- <p>Copyright &copy; Your Website 2014</p> -->\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.container -->\r\n");
      out.write("    <!-- jQuery -->\r\n");
      out.write("    <script src=\"WidgetClientPage/js/jquery.js\"></script>\r\n");
      out.write("    <!-- Bootstrap Core JavaScript -->\r\n");
      out.write("    <script src=\"WidgetClientPage/js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\t\n");
      out.write("\tfunction fun_develop(){\n");
      out.write("\t\tlocation.replace(\"/Develop.jsp\");\n");
      out.write("\t\t\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
