/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-09-06 16:40:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class Store_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");


	request.setCharacterEncoding("UTF-8");


      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta name=\"author\" content=\"\">\n");
      out.write("    <title>WidgetStore - STORE</title>\n");
      out.write("    <!-- Bootstrap Core CSS -->\n");
      out.write("    <link href=\"WidgetClientPage/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- Custom CSS -->\n");
      out.write("    <link href=\"WidgetClientPage/css/shop-homepage.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n");
      out.write("    <!--[if lt IE 9]>\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\n");
      out.write("    <![endif]-->\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body onload=\"init()\">\n");
      out.write("    <!-- Navigation -->\n");
      out.write("    <nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <!-- Brand and toggle get grouped for better mobile display -->\n");
      out.write("            <div class=\"navbar-header\">\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                </button>\n");
      out.write("                <a class=\"navbar-brand\" href=\"#\">WIDGET STORE</a>\n");
      out.write("            </div>\n");
      out.write("            <!-- Collect the nav links, forms, and other content for toggling -->\n");
      out.write("            <!-- ìì ë©ë´ -->\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\n");
      out.write("                <ul class=\"nav navbar-nav\">\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"Develop/Develop.jsp\">Develop</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\">Services</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <a href=\"#\">Contact</a>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <!-- /.navbar-collapse -->\n");
      out.write("        </div>\n");
      out.write("        <!-- /.container -->\n");
      out.write("    </nav>\n");
      out.write("    <!-- Page Content -->\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-md-3\">\n");
      out.write("                    <p class=\"lead\">WidgetStore</p>\n");
      out.write("                    <div class=\"list-group\">\n");
      out.write("                        <a href=\"#\" class=\"list-group-item\">ìí</a>\n");
      out.write("                        <a href=\"#\" class=\"list-group-item\">ì¤í¬ì¸ </a>\n");
      out.write("                        <a href=\"#\" class=\"list-group-item\">ê²ì</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-md-9\">\n");
      out.write("                    <!--\n");
      out.write("                    <div class=\"row carousel-holder\">\n");
      out.write("            \n");
      out.write("                        <div class=\"col-md-12\">\n");
      out.write("                            <div id=\"carousel-example-generic\" class=\"carousel slide\" data-ride=\"carousel\">\n");
      out.write("                                <ol class=\"carousel-indicators\">\n");
      out.write("                                    <li data-target=\"#carousel-example-generic\" data-slide-to=\"0\" class=\"active\"></li>\n");
      out.write("                                    <li data-target=\"#carousel-example-generic\" data-slide-to=\"1\"></li>\n");
      out.write("                                    <li data-target=\"#carousel-example-generic\" data-slide-to=\"2\"></li>\n");
      out.write("                                </ol>\n");
      out.write("                                <div class=\"carousel-inner\">\n");
      out.write("                                    <div class=\"item active\">\n");
      out.write("                                        <img class=\"slide-image\" src=\"over.jpg\" alt=\"\">\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"item\">\n");
      out.write("                                        <img class=\"slide-image\" src=\"closer.jpg\" alt=\"\">\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"item\">\n");
      out.write("                                        <img class=\"slide-image\" src=\"deon.jpg\" alt=\"\">\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <a class=\"left carousel-control\" href=\"#carousel-example-generic\" data-slide=\"prev\">\n");
      out.write("                                    <span class=\"glyphicon glyphicon-chevron-left\"></span>\n");
      out.write("                                </a>\n");
      out.write("                                <a class=\"right carousel-control\" href=\"#carousel-example-generic\" data-slide=\"next\">\n");
      out.write("                                    <span class=\"glyphicon glyphicon-chevron-right\"></span>\n");
      out.write("                                </a>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("            \n");
      out.write("                    </div>\n");
      out.write("                    -->\n");
      out.write("                    <!-- ìì¸ë³´ê¸° ë¶ë¶ -->\n");
      out.write("                    <div class='widgetInfo' id='widgetInfo' style=\"display: none;\">\n");
      out.write("                        <div>\n");
      out.write("                            <!-- ìì ¯ì ë©ì¸ ì¬ì§ê³¼ ìì±ì -->\n");
      out.write("                            <div class='goodsMain'>\n");
      out.write("                                <img src='http://placehold.it/150x150' alt=''>\n");
      out.write("                                <h1 id='widgetName'></h1>\n");
      out.write("                                <h4 id='widgetDeveloperName'></h4>\n");
      out.write("                                <h4 id='star'></h4>\n");
      out.write("                                <h5 id='grade'></h5>\n");
      out.write("                                <div class='btnBuy'>Download</div>\n");
      out.write("                            </div>\n");
      out.write("                            <!-- ìì ¯ì ì¤ëªì© ì¬ì§ê³¼ ì¤ëª -->\n");
      out.write("                            <div class='goodsSub'>\n");
      out.write("                                <img src='http://placehold.it/550x150' alt=''>\n");
      out.write("                                <h5 id='widgetExplain'></h5>\n");
      out.write("                            </div>\n");
      out.write("                            <!-- ë¦¬ë·° -->\n");
      out.write("                            <div class=\"well\">\n");
      out.write("                                <div class=\"row\">\n");
      out.write("                                    <div class=\"col-md-12\">\n");
      out.write("                                        <strong><ins>Comments</ins></strong>\n");
      out.write("                                        <span class=\"glyphicon glyphicon-pencil\"></span>\n");
      out.write("                                        <div class='goodsReview'>\n");
      out.write("                                            <div id='widgetReview'></div>\n");
      out.write("                                            <div>\n");
      out.write("                                                <!-- ë§ê¸ ë¤ë ë¶ë¶ -->\n");
      out.write("                                                <div class=\"dropdown\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<label>[ì¬ì©ì ID íì ë¶ë¶]</label>\n");
      out.write("                                                    <button class=\"btn btn-default dropdown-toggle\" type=\"button\" id=\"dropdownMenu1\" data-toggle=\"dropdown\" aria-expanded=\"true\">\n");
      out.write("    âââââ\n");
      out.write("    <span class=\"caret\"></span>\n");
      out.write("  </button>\n");
      out.write("                                                    <ul class=\"dropdown-menu\" role=\"menu\" aria-labelledby=\"dropdownMenu1\">\n");
      out.write("                                                        <li role=\"presentation\"><a role=\"menuitem\" tabindex=\"-1\" href=\"#\">âââââ</a></li>\n");
      out.write("                                                        <li role=\"presentation\"><a role=\"menuitem\" tabindex=\"-1\" href=\"#\">âââââ</a></li>\n");
      out.write("                                                        <li role=\"presentation\"><a role=\"menuitem\" tabindex=\"-1\" href=\"#\">âââââ</a></li>\n");
      out.write("                                                        <li role=\"presentation\"><a role=\"menuitem\" tabindex=\"-1\" href=\"#\">âââââ</a></li>\n");
      out.write("                                                        <li role=\"presentation\"><a role=\"menuitem\" tabindex=\"-1\" href=\"#\">âââââ</a></li>\n");
      out.write("                                                    </ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("                                                </div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("                                                <div class=\"input-group\">\n");
      out.write("                                                    <textarea id='msg' class=\"form-control\" rows=\"2\"></textarea>\n");
      out.write("                                                    <span class=\"input-group-btn\">\n");
      out.write("        <button class=\"btn btn-default btn-lg\" type=\"submit\">ëê¸ë±ë¡</button>\n");
      out.write("      </span>\n");
      out.write("                                                </div>\n");
      out.write("                                                <!-- /input-group -->\n");
      out.write("\n");
      out.write("\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div id=\"field\" class=\"row\">\n");
      out.write("                        <script type=\"text/javascript\">\n");
      out.write("                            function init() {\n");
      out.write("                                // dbìì ë¶ë¬ì¨ ìì ¯ì idì ë°ë¼ ì ì í ìì ¯ì ë¶ì.\n");
      out.write("                                addItem(1);\n");
      out.write("                                addItem(2);\n");
      out.write("                                addItem(3);\n");
      out.write("                                addItem(4);\n");
      out.write("                                addItem(5);\n");
      out.write("                                addItem(6);\n");
      out.write("                            }\n");
      out.write("\n");
      out.write("                            // ë§ê¸ì ë¤ë í¨ì\n");
      out.write("                            function submit() {\n");
      out.write("                                //\n");
      out.write("                                // ìë²ì ì ì¥íë ë¶ë¶ì´ íìí¨.\n");
      out.write("                                // \n");
      out.write("                                // \n");
      out.write("                                // \n");
      out.write("                                // \n");
      out.write("                                // \n");
      out.write("                                var text = document.getElementById('msg');\n");
      out.write("                                if (text.value == \"\") {\n");
      out.write("                                    alert(\"ë´ì©ì´ ìì\");\n");
      out.write("                                    return;\n");
      out.write("                                }\n");
      out.write("\n");
      out.write("                                showReview(\"ìì´ë\", text.value);\n");
      out.write("                                text.value = \"\";\n");
      out.write("                            }\n");
      out.write("\n");
      out.write("                            // ì ì²´ ë´ì©ì íìíë í¨ì\n");
      out.write("                            function open_detail(widgetId) {\n");
      out.write("                                // ì¨ê²¨ì¡ë í¼ì ë¡ëí¨.\n");
      out.write("                                if (!document.getElementById('widgetInfo').style.display == \"\") {\n");
      out.write("                                    document.getElementById('widgetInfo').style.display = '';\n");
      out.write("                                }\n");
      out.write("\n");
      out.write("                                if (typeof(reviews) != 'undefined') {\n");
      out.write("                                    document.getElementById('reviews').remove();\n");
      out.write("                                }\n");
      out.write("\n");
      out.write("                                document.getElementById(\"widgetName\").innerText = \"\" + widgetId + \"ì ìì ¯ ì´ë¦ì\";\n");
      out.write("                                document.getElementById('widgetDeveloperName').innerText = \"\" + widgetId + \"ì ê°ë°ì ì´ë¦ì\";\n");
      out.write("                                document.getElementById('grade').innerText = \"íì  :  4.5\";\n");
      out.write("                                document.getElementById('star').innerText = \"âââââ\";\n");
      out.write("                                document.getElementById('widgetExplain').innerText =\n");
      out.write("\n");
      out.write("                                    \"ì¤ëë ë ì°ë¦¬ ìíì´ ë§ ì«ê¸°ìë¤.\\n\"\n");
      out.write("\n");
      out.write("                                +\n");
      out.write("                                \"ë´ê° ì ì¬ì ë¨¹ê³  ëë¬´ë¥¼ íë¬ ê° ìì¼ë¡ ëì¬ ëì´ìë¤.\\n\"\n");
      out.write("\n");
      out.write("                                +\n");
      out.write("                                \"ì°ì¼ë¡ ì¬ë¼ìë ¤ëê¹ ë±ë¤ìì í¸ë¥´ëí¸ëë, íê³  ë­ì íìë¦¬ê° ì¼ë¨ì´ë¤.\\n\"\n");
      out.write("\n");
      out.write("                                +\n");
      out.write("                                \"ê¹ì§ ëë¼ì ê³ ê°ë¥¼ ëë ¤ë³´ë ìëëë¤ë¥´ë´, ë ëì´ ë ì¼ë¦¬ìë¤.\\n\"\n");
      out.write("\n");
      out.write("                                +\n");
      out.write("                                \"ì ìë¤ ìí(ì ëê°ì´ê° í¬ê³  ë ì¤ìë¦¬ê°ì´ ì¤ííê² ìê¸´ ë)\"\n");
      out.write("\n");
      out.write("                                +\n");
      out.write("                                \"ì´ ë©ì ë¦¬ ìì ì°ë¦¬ ìíì í¨ë¶ë¡ í´ë´ë ê²ì´ë¤.\\n\"\n");
      out.write("\n");
      out.write("                                +\n");
      out.write("                                \" ê·¸ê²ë ê·¸ë¥ í´ë´ë ê²ì´ ìëë¼ í¸ëë íê³  ë©´ëë¥¼ ìª¼ê³  ë¬¼ë¬ì°ë¤ê° ì¢ ì¬ì´ë¥¼ ëê³  ë í¸ëë íê³  ëª¨ê°ì§ë¥¼ ìª¼ìë¤. \\n\\n\"\n");
      out.write("\n");
      out.write("                                +\n");
      out.write("                                \"ê¹ì ì \\n\"\n");
      out.write("\n");
      out.write("                                +\n");
      out.write("                                \"<ëë°±ê½>\\n\";\n");
      out.write("\n");
      out.write("                                // ëê¸ì íë²ì ì§ì°ê¸° ìí´\n");
      out.write("                                // ëê¸ ë¶ë¸ì ëì ì¼ë¡ ì¶ê°í¨\n");
      out.write("\n");
      out.write("\n");
      out.write("                                var div = document.createElement('div');\n");
      out.write("                                div.id = 'reviews';\n");
      out.write("                                document.getElementById('widgetReview').appendChild(div);\n");
      out.write("\n");
      out.write("                                // ë§ê¸ì ë¡ëí¨\n");
      out.write("                                showReview(\"ëë°\", \"ì´ê²ë ëíí´ë³´ìì§\");\n");
      out.write("                                showReview(\"ë¼ì¸íë¥´í¸\", \"ë°ì¤í°ì¨ì´ ëê°ì ë¤\");\n");
      out.write("                                showReview(\"ì í¬ë«\", \"í­í ë°ìë¼\");\n");
      out.write("                            }\n");
      out.write("\n");
      out.write("                            function showReview(name, text) {\n");
      out.write("                                // ìì ¯ ë²í¸ì ë°ë¥¸ ë§ê¸ì íìí¨\n");
      out.write("\n");
      out.write("                                var div = document.createElement('div');\n");
      out.write("\n");
      out.write("                                var strHTML =\n");
      out.write("                                    \"<h4 id='userName'> \" + name + \" </h4>\" + \"<h5 id='userReview'>\" + text + \"</h5><hr>\";\n");
      out.write("\n");
      out.write("                                div.innerHTML = strHTML;\n");
      out.write("                                document.getElementById('reviews').appendChild(div);\n");
      out.write("                            }\n");
      out.write("\n");
      out.write("                            function addItem(widgetID) {\n");
      out.write("                                var div = document.createElement('div');\n");
      out.write("                                // ë°©ë² 1.\n");
      out.write("                                // div.innerHTML = document.getElementById('aaa').outerHTML;\n");
      out.write("                                // document.getElementById('field').appendChild(div);\n");
      out.write("\n");
      out.write("                                // ë°©ë² 2.\n");
      out.write("                                // divId : field ë´ë¶ì div ID\n");
      out.write("                                // document.getElementById('divId').innerHTML = document.getElementById('aaa').outerHTML;\n");
      out.write("\n");
      out.write("                                // ë°©ë² 3.\n");
      out.write("                                var strHTML =\n");
      out.write("                                    \"<div class='col-sm-4 col-lg-4 col-md-4' id ='testID\" + widgetID + \"'>\" + \"<div class='thumbnail'>\" + \"<img src='http://placehold.it/320x150' alt=''>\" + \"<div class='caption'>\" + \"<h4 class='pull-right'></h4>\" +\n");
      out.write("\n");
      out.write("                                    '<h4 ><a href=\"JavaScript:;\" onclick=\"JavaScript: open_detail(' + widgetID + ');\">' + widgetID + \"</a></h4>\" +\n");
      out.write("\n");
      out.write("                                    \"<p>ì´ê²ì ì¤íì©ì´ë¤.</p></div>\" + \"<div class='ratings'>\" + \"<p class='pull-right'>18 reviews</p>\" + \"</div></div></div>\";\n");
      out.write("\n");
      out.write("                                div.innerHTML = strHTML;\n");
      out.write("                                document.getElementById('field').appendChild(div);\n");
      out.write("                            }\n");
      out.write("                        </script>\n");
      out.write("                        <!--\n");
      out.write("                        <div class=\"col-sm-4 col-lg-4 col-md-4\" id=\"aaa\">\n");
      out.write("                            <div class=\"thumbnail\">\n");
      out.write("                                <img src=\"http://placehold.it/320x150\" alt=\"\">\n");
      out.write("                                <div class=\"caption\">\n");
      out.write("                                    <h4 class=\"pull-right\"></h4>\n");
      out.write("                                    <h4><a href=\"JavaScript:;\" onclick=\"JavaScript: open_detail('1');\">Fifth Product</a></h4>\n");
      out.write("                                    <p>ìí</p>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"ratings\">\n");
      out.write("                                    <p class=\"pull-right\">18 reviews</p>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        -->\n");
      out.write("                        <!--\n");
      out.write("                        <div class=\"col-sm-4 col-lg-4 col-md-4\">\n");
      out.write("                            <h4><a href=\"#\">View more Widget?</a>\n");
      out.write("                            </h4>\n");
      out.write("                            <p>If you like this template, then check out <a target=\"_blank\" href=\"http://maxoffsky.com/code-blog/laravel-shop-tutorial-1-building-a-review-system/\">this tutorial</a> on how to build a working review system for your online store!</p>\n");
      out.write("                            <a class=\"btn btn-primary\" target=\"_blank\" href=\"http://maxoffsky.com/code-blog/laravel-shop-tutorial-1-building-a-review-system/\">View Tutorial</a>\n");
      out.write("                        </div>\n");
      out.write("                        -->\n");
      out.write("                        <!-- íì´ì§ ì»¨í¸ë¡¤ -->\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"pageWrap\">\n");
      out.write("                        <ul class=\"pageControl\">\n");
      out.write("                            <li><a href=\"\"> ì´ì </a></li>\n");
      out.write("                            <li><a href=\"\"> 1</a></li>\n");
      out.write("                            <li><a href=\"\"> 2</a></li>\n");
      out.write("                            <li><a href=\"\"> 3</a></li>\n");
      out.write("                            <li><a href=\"\"> 4</a></li>\n");
      out.write("                            <li><a href=\"\"> 5</a></li>\n");
      out.write("                            <li><a href=\"\"> 6</a></li>\n");
      out.write("                            <li><a href=\"\"> 7</a></li>\n");
      out.write("                            <li><a href=\"\"> 8</a></li>\n");
      out.write("                            <li><a href=\"\"> 9</a></li>\n");
      out.write("                            <li><a href=\"\"> 10</a></li>\n");
      out.write("                            <li><a href=\"\"> ì´í</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- /.container -->\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <hr>\n");
      out.write("        <!-- Footer -->\n");
      out.write("        <footer>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-12\">\n");
      out.write("                    ì ìì : ããã\n");
      out.write("                    <!-- <p>Copyright &copy; Your Website 2014</p> -->\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </footer>\n");
      out.write("    </div>\n");
      out.write("    <!-- /.container -->\n");
      out.write("    <!-- jQuery -->\n");
      out.write("    <script src=\"WidgetClientPage/js/jquery.js\"></script>\n");
      out.write("    <!-- Bootstrap Core JavaScript -->\n");
      out.write("    <script src=\"WidgetClientPage/js/bootstrap.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
